### ISSUE TITLE
3.3.4格式化正常，3.3.6/3.3.7格式化异常

### ISSUE THREAD

**Issue by anjia0532** [gejun123456/MyBatisCodeHelper-Pro#1026]
```bash
IntelliJ IDEA 2024.3.1.1 (Ultimate Edition)
Build #IU-243.22562.218, built on December 18, 2024
Runtime version: 21.0.5+8-b631.28 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 10240M
Cores: 12
```
![image](https://github.com/user-attachments/assets/3e85896d-0e48-412b-aee5-916024a0963c)

都是选中SQL后，Ctrl+Alt+L格式化，其余 idea 配置都一样。
3.3.4 正常
![image](https://github.com/user-attachments/assets/0c25354d-f979-41ee-950e-7bdd2baf8a1d)

3.3.7 全部靠左
![image](https://github.com/user-attachments/assets/dca608f5-0b11-4850-b6db-ae49912afd0e)

**Comment by gejun123456** [comment]
可以来个完整的sql 看看吗，插件用的是带marketplace edition的版本吗

**Comment by anjia0532** [comment]
插件 [3.3.7+2321](https://plugins.jetbrains.com/plugin/14522-mybatiscodehelperpro-marketplace-edition-/versions/stable/639027) 和 [3.3.6+2321](https://plugins.jetbrains.com/plugin/14522-mybatiscodehelperpro-marketplace-edition-/versions/stable/618365) 不行，[3.3.4+2321](https://plugins.jetbrains.com/plugin/14522-mybatiscodehelperpro-marketplace-edition-/versions/stable/575424) 可以。

```sql
SELECT od.order_id as `key`,
             od.id
FROM oms_order_detail od
```

**Comment by gejun123456** [comment]
![image](https://github.com/user-attachments/assets/4c9b0d5b-e91f-4ef4-b5c6-23c557bfab4f)
我这边没发现问题，可以加我微信 gejun12311 来看看

**Comment by anjia0532** [comment]
卸载插件重装也不行，最后把idea的设置导出后，把idea设置重置，然后再导入就行了
