### ISSUE TITLE
离线激活支持

### ISSUE THREAD

**Issue by CodingOX** [gejun123456/MyBatisCodeHelper-Pro#111]
还是提一个吧，希望增加离线激活。
公司内部电脑，无法连接外网！
3Q!

**Comment by gejun123456** [comment]
这个问题我想了想，有点难做。有没有其他方式可以联网哈，比如手机弄个热点，电脑装个无线网卡这种。

**Comment by gejun123456** [comment]
可以加下我微信哈，我们私聊下哈。

**Comment by CodingOX** [comment]
😰，公司乱插这些是违规的，要被fire。
MarkEditor 这个工具提供了离线激活！ 先生成本地码，然后进入某个网址，输入本地码后生成激活码，激活。使用离线激活有限制，365天内激活不能超过N次，大概是这样。

**Comment by gejun123456** [comment]
我想到了离线激活的方案了哈，这几天我弄弄

**Comment by gejun123456** [comment]
MyBatisCodeHelper-Pro-1.8.3.zip

**Comment by gejun123456** [comment]
[MyBatisCodeHelper-Pro-1.8.3.zip](https://github.com/gejun123456/MyBatisCodeHelper-Pro/files/2126379/MyBatisCodeHelper-Pro-1.8.3.zip)
这个版本支持了离线激活哈
![default](https://user-images.githubusercontent.com/6340473/41758977-70d86d48-761e-11e8-878d-cda6dc450861.png)
