### ISSUE TITLE
激活码失效的条件是什么？

### ISSUE THREAD

**Issue by nszaaa3** [gejun123456/MyBatisCodeHelper-Pro#124]
环境:
个人电脑
系统Ubuntu Gnome 16.04(Linux),
IDEA版本2018.1.4
插件版本1.8.0

问题:
今早买了激活码并在上述环境中使用了一个，
下午安装KDE桌面，不好用就卸载了KDE桌面，继续使用Gnome桌面，但切换回之后打开IDEA发现激活码已经失效，实际用了不到半天。
请问有什么解决方案？

**Comment by nszaaa3** [comment]
但是按Alt+Insert调出来的 generate mybatis files确实可以使用。我这是激活了还是没有激活。。。。

**Comment by gejun123456** [comment]
这些功能能正常用就是激活了的。有问题可以直接微信联系我哈

**Comment by nszaaa3** [comment]
原来是被event log这个浓眉大眼的家伙骗了。。感谢您的plugin，很棒！

**Comment by gejun123456** [comment]
好的哈，谢谢支持
