### ISSUE TITLE
可否放弃收费，转向开源

### ISSUE THREAD

**Issue by Zephery** [gejun123456/MyBatisCodeHelper-Pro#140]
这插件是真的不错，但是不提供源码，想在此之上做二次开发，比如加入tk.mybatis，lombook这些。不知楼主能否由收费转向开源捐赠模式？或者。。。我直接反编译，然后二次开发，不知大佬是否介意？

**Comment by gejun123456** [comment]
不能，可以提issue给我 tk.mybatis，lombook 我也在考虑接入，可以加我微信 和 我讨论下
