### ISSUE TITLE
能支持这个？

### ISSUE THREAD

**Issue by CodingOX** [gejun123456/MyBatisCodeHelper-Pro#143]
![image](https://user-images.githubusercontent.com/9800933/41913963-521b03ac-7984-11e8-9424-01aaade50276.png)

不能够注入的问题！

**Comment by gejun123456** [comment]
可以支持的，我看看怎么弄下。

**Comment by gejun123456** [comment]
我这两天在看这块，请问下你使用的是xml的配置吗，有用到 org.mybatis.spring.mapper.MapperScannerConfigurer 这个类来配置吗
我准备先实现一个简单一点的版本，查找xml中这个的配置 然后注入到spring中
之后再来支持@Mapper注解这种

**Comment by CodingOX** [comment]
我用的是通用mapper作者提供的开源的。他的项目地址是：
https://github.com/abel533/MyBatis-Spring-Boot
和这个：
https://github.com/abel533/Mybatis-Spring

**Comment by gejun123456** [comment]
好的 我看看这块

**Comment by gejun123456** [comment]
[MyBatisCodeHelper-Pro-1.8.4.zip](https://github.com/gejun123456/MyBatisCodeHelper-Pro/files/2162755/MyBatisCodeHelper-Pro-1.8.4.zip)
这个版本添加了spring的支持，可以试下 有问题随时反馈哈

**Comment by CodingOX** [comment]
完美解决！暂时没有发现问题。
