### ISSUE TITLE
您好，请问为什么不能自动生成Mapper呢

### ISSUE THREAD

**Issue by complone** [gejun123456/MyBatisCodeHelper-Pro#145]
![error](https://user-images.githubusercontent.com/20021404/42161609-25a0cae2-7e2e-11e8-9986-322dfd5d99ad.png)

**Comment by complone** [comment]
打错了，是没有自动生成xml

**Comment by gejun123456** [comment]
检查下你的xml 里面的resultmap，和 User类的属性是否能一一对上，是不是少了啥属性

**Comment by complone** [comment]
![index](https://user-images.githubusercontent.com/20021404/42163148-008dd37a-7e34-11e8-9ac0-1ddfa3ceb39d.png)
所以如果带有List返回类型的话不行对么

**Comment by gejun123456** [comment]
把这个list的属性设置为    private transient 即可

类似于 private transient List<Role> roles
