### ISSUE TITLE
icon 支持高分屏

### ISSUE THREAD

**Issue by Elderry** [gejun123456/MyBatisCodeHelper-Pro#150]
如图：
![image](https://user-images.githubusercontent.com/1892221/43385164-9b8433bc-9412-11e8-9bef-dd6fcf5b72f6.png)
![image](https://user-images.githubusercontent.com/1892221/43385449-5ec0f27a-9413-11e8-8ac0-2385be657fb6.png)
Intellij 最近更新了图标，增加了分辨率并使其风格一致化，建议本项目图标也修正下。

**Comment by gejun123456** [comment]
ok 我看看这块，谢谢建议

**Comment by gejun123456** [comment]
1.8.9版本分辨率优化了下 可以看 #160  可以加qq群：542735979 群文件有最新版，IDEA仓库估计要2天审核

**Comment by Elderry** [comment]
辛苦了，非常期待🤪
