### ISSUE TITLE
优化通过数据库生成时的注释

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/MyBatisCodeHelper-Pro#156]
java类不用加多余的注释

**Comment by gejun123456** [comment]
只需保留model层来自于数据库的注释

**Comment by Gkirito** [comment]
最好就单独加个选项只生成model层来自于数据库的注释，然后XML和接口中也不生成注释。Thanks♪(･ω･)ﾉ5

**Comment by gejun123456** [comment]
1.8.9版本已支持，可以加qq群542735979 下载新版本 IDEA仓库估计要2天审核

**Comment by Gkirito** [comment]
好的，谢谢
