### ISSUE TITLE
跳转XML文件图标 在高清屏下 太模糊了

### ISSUE THREAD

**Issue by qinkangdeid** [gejun123456/MyBatisCodeHelper-Pro#160]
很好的插件 后续希望能一直用下去  有个纠结的问题 那就是 4K屏下 跳转XML文件图标 在高清屏下 太模糊了💔
<img width="138" alt="wx20180810-232639 2x" src="https://user-images.githubusercontent.com/17582522/43966883-a54ed352-9cf5-11e8-8ad1-ef8ce2e8faf0.png">

**Comment by gejun123456** [comment]
好的哈 我想想，谢谢反馈

**Comment by qinkangdeid** [comment]
使用这个版本的图标  很清晰了 也很好看 比以前的鸟好一些 haha~~  谢谢 
![image](https://user-images.githubusercontent.com/17582522/44385511-33d07180-a552-11e8-9f8b-54856c85a357.png)
