### ISSUE TITLE
每当第一次开启对应Tool Buttons IDEA会停止响应一段时间

### ISSUE THREAD

**Issue by RichardLiu0926** [gejun123456/MyBatisCodeHelper-Pro#167]

**Comment by gejun123456** [comment]
请问下插件是啥版本。还有Intellij的版本是？

**Comment by gejun123456** [comment]
可以加我qq：1098632410 来详细看看

**Comment by RichardLiu0926** [comment]
当我删除 data sources设置就不会出现卡顿无响应。我估计打开面板加载数据库信息阻塞了idea主线程




| |
Richard Liu(刘勇)
邮箱：richardliu0926@163.com
|

签名由 网易邮箱大师 定制

在2018年08月22日 20:46，葛俊 写道：

可以加我qq：1098632410 来详细看看

**Comment by gejun123456** [comment]
2.0.2 版本已优化，可以在群文件下载
