### ISSUE TITLE
idea中@Autowired下的mapper接口还是报红线

### ISSUE THREAD

**Issue by JunJYu** [gejun123456/MyBatisCodeHelper-Pro#182]
用的是@MapperScan

**Comment by gejun123456** [comment]
[MyBatisCodeHelper-Pro-1.9.5-SNAPSHOT-IDEA173-IDEA182.zip](https://github.com/gejun123456/MyBatisCodeHelper-Pro/files/2355929/MyBatisCodeHelper-Pro-1.9.5-SNAPSHOT-IDEA173-IDEA182.zip)

支持版本支持的mapperScan是 tk.mybatis.spring.annotation.MapperScan

这个我修复了，可以下载这个版本试试
