### ISSUE TITLE
有选择性地生成Mapper.xml

### ISSUE THREAD

**Issue by zhady009** [gejun123456/MyBatisCodeHelper-Pro#193]
希望可以选择生成的内容 比如我只想要BaseResultMap或者BaseColumnList 

因为用了通用Mapper剩下的内容就没什么用了 如果表很多一个一个删比较麻烦

**Comment by gejun123456** [comment]
嗯，是指用 数据库来生成crud的时候吗， 我想想看能不能加个选项。

**Comment by gejun123456** [comment]
2.0.2 支持从从数据一键生成通用mapper代码，xml中只有 BaseResultMap和BaseColumnList
可以群文件中下载到
