### ISSUE TITLE
POJO类中的任何布尔类型的变量，都不要加is前缀

### ISSUE THREAD

**Issue by cxk1029** [gejun123456/MyBatisCodeHelper-Pro#198]
参考 阿里巴巴 建表规约
链接：chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/https://alitech-private.oss-cn-beijing.aliyuncs.com/1528269849853/Java_manual.pdf?Expires=1538992861&OSSAccessKeyId=LTAIgu8IHyutlWfc&Signature=Rj32MVTCbrtqmd619MliAVcH9ak%3D
文章中关键字段索引："POJO类中的任何布尔类型的变量，都不要加is前缀"

**Comment by gejun123456** [comment]
嗯，和我的插件有关系么。

**Comment by cxk1029** [comment]
用你的插件，很多生成的语法 潜移默化的已经 成为一种规范
作为菜鸟的我只是 弱弱的提一下
