### ISSUE TITLE
Spring Boot中无法识别为Spring Bean

### ISSUE THREAD

**Issue by jaune162** [gejun123456/MyBatisCodeHelper-Pro#228]
配置了
```java
@SpringBootApplication(scanBasePackages = "com.wawscm.shangde")
@MapperScan(basePackages = "com.wawscm.shangde.module.**.mapper")
```
![image](https://user-images.githubusercontent.com/10142624/48966281-7601c700-f009-11e8-9989-fa69689d1a80.png)

仍然不能识别为Spring Bean，求解决方法

我要怎么弄才能支持spring bean，我看文档中写的是支持的。强迫症患者，快疯了，大佬救我！

**Comment by jaune162** [comment]
另外希望支持`tk.mybatis.mapper`中的`@MapperScan`

**Comment by jaune162** [comment]
已确定问题是由`*`号引起的。

- `**`匹配多个包, `com.github.**.mapper`匹配`com.github.x.y.mapper`,`com.github.x.y.z.mapper`,`com.github.mapper`,`com.github.x.mapper`
- `*`匹配一级`com.github.**.mapper`匹配`com.github.x.mapper`

希望大佬处理的时候注意下

**Comment by gejun123456** [comment]
谢谢反馈，明天我搞搞

**Comment by jaune162** [comment]
搞定了吗？什么时候发布新版本？

**Comment by gejun123456** [comment]
还没，今天还要搞搞

**Comment by gejun123456** [comment]
已经可以了，我发群文件罗。可以试试
