### ISSUE TITLE
java和xml互相跳转的图标不是特别高清...

### ISSUE THREAD

**Issue by flamhaze5946** [gejun123456/MyBatisCodeHelper-Pro#23]
这个如果有时间希望可以修复一下 = =

**Comment by gejun123456** [comment]
哈哈，我看看，能找到高清图就做上去

**Comment by flamhaze5946** [comment]
谢啦, 毕竟稍微有点违和 👍

**Comment by gejun123456** [comment]
[MyBatisCodeHelper-Pro-1.6.7.zip](https://github.com/gejun123456/MyBatisCodeHelper-Pro/files/1220433/MyBatisCodeHelper-Pro-1.6.7.zip)
弄了个高清版的，图片太小了，有点难看出来，可以看看。
