### ISSUE TITLE
一个Mapper对应多个xml的时候，列表中应该列出是xml文件名

### ISSUE THREAD

**Issue by jaune162** [gejun123456/MyBatisCodeHelper-Pro#233]
![image](https://user-images.githubusercontent.com/10142624/49137887-b3779480-f328-11e8-9cf7-044367d284df.png)

like this
![image](https://user-images.githubusercontent.com/10142624/49137896-bb373900-f328-11e8-8ce2-12992f0e682a.png)

**Comment by gejun123456** [comment]
嗯，是的，可以支持下

**Comment by gejun123456** [comment]
已经支持了，群文件可以下载。
