### ISSUE TITLE
添加很多表的数据源时会卡死

### ISSUE THREAD

**Issue by yongdi** [gejun123456/MyBatisCodeHelper-Pro#234]
有些环境即便非生产仍然有很多表，可能是生成映射关系时耗费资源或者别的，反正会在add database config这个界面卡住不动，什么都做不了，而且无穷无尽∞ 😓
![wx20181129-202656](https://user-images.githubusercontent.com/6258251/49221811-252d0c80-f415-11e8-8644-841b8a94b07e.png)

**Comment by gejun123456** [comment]
嗯，这个在优化，是Intellij高级版么，可以直接在Intellij高级版上的数据库 表上操作的，一样的效果

**Comment by gejun123456** [comment]
还可以加个新库，把表给建过来。你们一个库大概有多少张表，我明天测测

**Comment by gejun123456** [comment]
是远程的数据库么，我试了下本地的数据库 1000张表 很快就好了，可以加我qq 1098632410 详细了解下

**Comment by gejun123456** [comment]
我找到了可以优化的地方，明天弄下

**Comment by gejun123456** [comment]
2.0.2 支持罗，群文件可以下载到
