### ISSUE TITLE
希望在生成Mapper的时候可以选择Mapper继承的接口

### ISSUE THREAD

**Issue by jaune162** [gejun123456/MyBatisCodeHelper-Pro#235]
![image](https://user-images.githubusercontent.com/10142624/49262653-6dcedf00-f482-11e8-9530-143cb8d5ffe0.png)

![image](https://user-images.githubusercontent.com/10142624/49262663-7c1cfb00-f482-11e8-850e-c1c95b7dc019.png)

像这样

**Comment by jaune162** [comment]
tk.mapper和mybatis-plus这两个插件应该是现在用的比较多的插件，感觉大佬可以集成一下，可以生成对应的Mapper

**Comment by gejun123456** [comment]
tk.mapper 已经集成好了 ，到时我再集成下 mybatisPlus

**Comment by gejun123456** [comment]
群文件最新版 已经集成了mybatisPlus了 可以试试
