### ISSUE TITLE
优化提示

### ISSUE THREAD

**Issue by jaune162** [gejun123456/MyBatisCodeHelper-Pro#238]
![image](https://user-images.githubusercontent.com/10142624/49349526-f26d6780-f6e5-11e8-88bd-2419cba16521.png)

改为明确的提示。
- Create select statement in xml mapper
- Create insert statement in xml mapper
- Create update statement in xml mapper
- Create delete statement in xml mapper

> 提示信息大佬可以自己优化，第一个单词首字母大写，其他的提示信息应该也是首字母大写的（这样显得更加专业一点儿）

前缀
- select -> get,find,select,query
- insert -> save, insert
- update -> update, modify, change
- delete -> delete, remove

默认select

**Comment by jaune162** [comment]
最好是能做成前缀可配置的

**Comment by gejun123456** [comment]
哇 这个好 谢谢建议

**Comment by gejun123456** [comment]
已支持
