### ISSUE TITLE
优化Mapper中字段的生成

### ISSUE THREAD

**Issue by jaune162** [gejun123456/MyBatisCodeHelper-Pro#260]
![image](https://user-images.githubusercontent.com/10142624/50067632-b74a5880-01fc-11e9-886c-bbe28d696fb1.png)

现在生成的格式是这样的
![image](https://user-images.githubusercontent.com/10142624/50067640-ca5d2880-01fc-11e9-8858-0d5debd77b09.png)

能否根据字段类型添加jdbcType，然后将Bean属性名按照首字母大写的规则拆分成多个单词，然后用下滑线连接作为数据库字段名，直接生成成下图的代码
![image](https://user-images.githubusercontent.com/10142624/50067725-435c8000-01fd-11e9-90b1-9449e91bc048.png)

**Comment by gejun123456** [comment]
已支持，群文件可以下载，谢谢建议。
