### ISSUE TITLE
PostgreSQL 表和字段有加双引号 导致插在无法生产 dao xml entrity

### ISSUE THREAD

**Issue by colryzen** [gejun123456/MyBatisCodeHelper-Pro#264]
PostgreSQL 数据库对大小写敏感
表面和字段名 有 加双引号（“”），导致插件无法识别到表，无法生成相关文件

**Comment by gejun123456** [comment]
可以看下建表语句吗，我试试

**Comment by gejun123456** [comment]
用intellij自带的那个数据库也有问题么

**Comment by colryzen** [comment]
CREATE TABLE "C_Attachment" (
"id" varchar(50) NOT NULL,
"uploadDatetime" timestamptz(0),
"name" varchar(50),
"filesize" varchar(50),
"fileFormat" varchar(50),
"url" varchar(255),
"remark" varchar(255),
"categoryId" varchar(50),
PRIMARY KEY ("id") ,
CONSTRAINT "fk_attachment" FOREIGN KEY ("categoryId") REFERENCES "C_AttachmentCategory" ("categoryId")
)
WITHOUT OIDS;

COMMENT ON TABLE "C_Attachment" IS '企业附件分类';
COMMENT ON COLUMN "C_Attachment"."id" IS '附件编号';
COMMENT ON COLUMN "C_Attachment"."uploadDatetime" IS '上传时间';
COMMENT ON COLUMN "C_Attachment"."name" IS '文件名称';
COMMENT ON COLUMN "C_Attachment"."filesize" IS '文件大小';
COMMENT ON COLUMN "C_Attachment"."fileFormat" IS '文件格式';
COMMENT ON COLUMN "C_Attachment"."url" IS '下载地址';
COMMENT ON COLUMN "C_Attachment"."remark" IS '备注';
COMMENT ON COLUMN "C_Attachment"."categoryId" IS '分类编号';

**Comment by gejun123456** [comment]
我可以生成的，联系我qq 1098632410 我来远程看看

**Comment by gejun123456** [comment]
![default](https://user-images.githubusercontent.com/6340473/51094660-d6330f00-17e9-11e9-8245-bd5e8b27276b.gif)
