### ISSUE TITLE
补一些需求

### ISSUE THREAD

**Issue by JVMAK** [gejun123456/MyBatisCodeHelper-Pro#270]
1.   mapper.xml中的jdbcType设置配置选项，是否需要生成。
2.   抽取基础的baseMapper

**Comment by gejun123456** [comment]
jdbcType这个2.4 支持 可以群文件下载

抽取基础BaseMapper这个要看看 不同mapper生成的方法可能不一样

**Comment by gejun123456** [comment]
2.5 已支持
