### ISSUE TITLE
生成service方法时,没有在接口中一并生成方法

### ISSUE THREAD

**Issue by raydl007** [gejun123456/MyBatisCodeHelper-Pro#272]

**Comment by gejun123456** [comment]
是否使用 通用mapper这个， 通用mapper目前不会在service中生成方法

**Comment by raydl007** [comment]
是通过在Mapper.java中,生成的
![image](https://user-images.githubusercontent.com/10443318/50877596-7f09f480-140d-11e9-92e4-ecde0faba38a.png)

![image](https://user-images.githubusercontent.com/10443318/50877574-6ac5f780-140d-11e9-9f62-057ed9b91991.png)
