### ISSUE TITLE
在Mapper.java中,生成的service中方法,没有生成对应的接口

### ISSUE THREAD

**Issue by raydl007** [gejun123456/MyBatisCodeHelper-Pro#278]
是通过在Mapper.java中,生成的
![image](https://user-images.githubusercontent.com/10443318/50877596-7f09f480-140d-11e9-92e4-ecde0faba38a.png)

![image](https://user-images.githubusercontent.com/10443318/50877574-6ac5f780-140d-11e9-9f62-057ed9b91991.png)

_Originally posted by @raydl007 in https://github.com/gejun123456/MyBatisCodeHelper-Pro/issues/272#issuecomment-452571526_

**Comment by gejun123456** [comment]
有报错么，我这边可以正常生成 可以联系我qq 1098632410 我来看看

**Comment by gejun123456** [comment]
![service](https://user-images.githubusercontent.com/6340473/50900168-586cad80-144f-11e9-8b0c-f7055fed2c4e.gif)
