### ISSUE TITLE
IntelliJ IDEA 2018.2.5不支持

### ISSUE THREAD

**Issue by shijiebei2009** [gejun123456/MyBatisCodeHelper-Pro#279]
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
Licensed to lan yu
Subscription is active until May 5, 2019
JRE: 1.8.0_152-release-1248-b19 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

**Comment by gejun123456** [comment]
发现用的是 Ibatis 不支持Ibatis
