### ISSUE TITLE
generate java class功能增强

### ISSUE THREAD

**Issue by optimistic9527** [gejun123456/MyBatisCodeHelper-Pro#280]
![image](https://user-images.githubusercontent.com/37545032/50955813-02524580-14f5-11e9-80ac-40d78919d16e.png)
提供Lombok注解，序列化，以及对数据字段的勾选

**Comment by gejun123456** [comment]
可以的

**Comment by gejun123456** [comment]
计划将其移到mybatis generator的菜单中

添加一个只生成实体类的按钮

**Comment by optimistic9527** [comment]
@gejun123456 可以，那个lombok可以考虑一下变成一个下拉框进行选择，默认给几个就好了，要不然一个@Data太多，不太好

**Comment by gejun123456** [comment]
可以的，谢谢建议

**Comment by optimistic9527** [comment]
@gejun123456 能不能先做这个功能，:see_no_evil:，在做微服务的时候太多这种单个的实体类了，一个一个写好累啊

**Comment by gejun123456** [comment]
明天弄下

**Comment by gejun123456** [comment]
群文件已支持
