### ISSUE TITLE
SelectProvider 会跳转到错误的方法上

### ISSUE THREAD

**Issue by igaozp** [gejun123456/MyBatisCodeHelper-Pro#295]
例如有两个 Maven 模块 A 和 B，A 和 B 中都包含 CommonDao 类和 CommonDaoProvider 类且里面的接口名称相同，A 中的 CommonDao 的 SelectProvider 接口会跳转到 B 中的 SelectProvider 方法上，按理说应该跳转到 A 中的 SelectProvider 方法上。

**Comment by gejun123456** [comment]
目前是按当前project来找的 会不确定找到哪个

我修一下

**Comment by gejun123456** [comment]
已支持
