### ISSUE TITLE
selectKey 报红

### ISSUE THREAD

**Issue by raydl007** [gejun123456/MyBatisCodeHelper-Pro#305]
![image](https://user-images.githubusercontent.com/10443318/53927148-d6041100-40c0-11e9-8a7a-a3c77555be14.png)

**Comment by gejun123456** [comment]
完整的sql 可以看下么

**Comment by gejun123456** [comment]
我知道了，我修复一下

**Comment by gejun123456** [comment]
修复好了，可以去qq群下载 542735979

**Comment by raydl007** [comment]
嗯嗯,谢啦
