### ISSUE TITLE
xml中 @Mbg generated 注释太长  

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/MyBatisCodeHelper-Pro#322]
只保留一个 \@Mbg generated 的注释 就可以了

**Comment by mbg** [comment]
I think you tagged the wrong person

**Comment by gejun123456** [comment]
i'm sorry, here the @ is meaning java annotation value.

**Comment by mbg** [comment]
Ah, in that case, if you use markdown to format it as a code (e.g. `@mbg`), it won't act as a tag on GitHub.

**Comment by gejun123456** [comment]
Thanks alot, sorry for bothering you, will close this.
