### ISSUE TITLE
总是跳转到编译后的classes目录下XML文件

### ISSUE THREAD

**Issue by mozun** [gejun123456/MyBatisCodeHelper-Pro#330]
快速跳转的时候每次都是跳转到了编译后的classes目录下的XML文件中，能否直接跳转到项目源代码目录resource文件目录下的源文件？谢谢

**Comment by gejun123456** [comment]
快速跳转 是指用 快捷键跳转吗 还是用图标  如果有多个的话 图标的话 会选择的

**Comment by gejun123456** [comment]
另外编译后的class  直接 IDEA exclude下 就不会找到了的

**Comment by mozun** [comment]
> 快速跳转 是指用 快捷键跳转吗 还是用图标 如果有多个的话 图标的话 会选择的

快捷键跳转

**Comment by gejun123456** [comment]
对了 编译后的class 没有 exclude掉么 我来优化下

**Comment by mozun** [comment]
> 对了 编译后的class 没有 exclude掉么 我来优化下

目前看到是没有的，感谢

**Comment by gejun123456** [comment]
编译后的class 比如 target 目录 为啥不exclude掉呢

**Comment by mozun** [comment]
> 编译后的class 比如 target 目录 为啥不exclude掉呢

工程使用gradle的时候都没有定义exclude掉这些目录，基本很少会去修改这些，所以基本不会留意到。这个插件能优化得了吗？谢谢

**Comment by gejun123456** [comment]
idea 在文件夹上右键 mark directory as exclude

**Comment by mozun** [comment]
好的，谢谢
