### ISSUE TITLE
新功能点：方法中带List参数时，自动生成foreach语句

### ISSUE THREAD

**Issue by JamesChenX** [gejun123456/MyBatisCodeHelper-Pro#333]
我有一个类似于：
`int insertList(List<UserMsg> records);`
的方法。
每次都要在XML中重复书写foreach语句，很是繁琐。
能否考虑下提供自动生成foreach语句的功能？

**Comment by gejun123456** [comment]
有的，自带就能生成insertList  2.5 版本有个 moresql 选中batchInsert那个就行 

或者通过方法名insertList 也可以生成

**Comment by gejun123456** [comment]
另外在xml 中可以 通过 co 来生成 foreach 语句

**Comment by JamesChenX** [comment]
大哥，我哭了。你这插件实在太好用了。
我给你宣传去

**Comment by gejun123456** [comment]
谢谢支持，有问题随时联系:)
