### ISSUE TITLE
新功能点：select获取指定字段值，而不是所有字段（即整个对象）

### ISSUE THREAD

**Issue by JamesChenX** [gejun123456/MyBatisCodeHelper-Pro#334]
比如可能一个row对应了：name、password、id，这三个字段。
但通常情况下，我们只是想要其中一个password字段。
传统上是：select(long id)来获取整个对象（即三个字段都获得），但这过于浪费IO与内存了。
能否提供：根据类似于selectPasswordById()这样的方法，自动生成对应的XML？
因为自己手写的话很是繁琐，经常需要大量自己手些XML来获得指定的字段。
先谢谢了

**Comment by gejun123456** [comment]
方法名生成sql 不行么， 应该支持的

**Comment by gejun123456** [comment]
https://gejun123456.github.io/MyBatisCodeHelper-Pro/#/methodNameToSql

**Comment by JamesChenX** [comment]
@gejun123456 你好。刚刚又研究下了用法，成功了。谢谢老哥。
原来是这么回事：如果我只输入“”findPhoneByEmail“，就能生成对应的sql。
但是如果输入”findPhoneByEmail(String email)“，就只能生成空XML标签了。
一会发朋友圈给朋友分享分享你这插件，太好用了

**Comment by gejun123456** [comment]
是的，不需要返回值和参数   谢谢支持
