### ISSUE TITLE
手机扫不了二维码，无法支付

### ISSUE THREAD

**Issue by wujunshen** [gejun123456/MyBatisCodeHelper-Pro#350]
可否提供支付宝网页登陆付款功能。付款二维码无法扫

**Comment by gejun123456** [comment]
不能，可以直接联系我微信 我发送支付宝二维码扫

**Comment by wujunshen** [comment]
那可否提供你的微信？

**Comment by gejun123456** [comment]
https://raw.githubusercontent.com/gejun123456/MyBatisCodeHelper-Pro/master/screenshots/wechatme.png

**Comment by wujunshen** [comment]
多谢，微信上聊
