### ISSUE TITLE
xml 中无法正常识别 collection 属性

### ISSUE THREAD

**Issue by SxunS** [gejun123456/MyBatisCodeHelper-Pro#365]
实体类如下：
`package com.bokesoft.cnooc.service.app.domain;

import lombok.Data;

@Data
public class TOrderItem {

	private Long id;

	private String orderNo;

}`

xml如下：
`<resultMap id="tOrderHeaderMap" type="com.bokesoft.cnooc.service.app.domain.TOrderHeader">
        <id property="id" column="oid" javaType="long"/>
        <result property="no" column="No" javaType="string"/>
        <collection property="items" javaType="com.bokesoft.cnooc.service.app.domain.TOrderItem">
            <id property="id" column="loid" javaType="long"/>
            <result property="orderNo" column="OrderNo" javaType="string"/>
        </collection>
    </resultMap>`

其中collection 中的id 和 result 均不识别，如果是我配置有问题，给您造成了不便，还请多多包涵。期待您的回复！

**Comment by gejun123456** [comment]
collection 应该配置 ofType 不是 javaType 
可以看看https://blog.csdn.net/u013216156/article/details/78642920
