### ISSUE TITLE
支持Instant类型

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/MyBatisCodeHelper-Pro#370]
数据库生成crud 设置中提供一个选项 useInstantForLocalDateTime 选项

**Comment by gejun123456** [comment]
2.7已解决

**Comment by gejun123456** [comment]
选项还没弄。

**Comment by linjunzhu** [comment]
@gejun123456  请问这个支持了吗？在设置内没找到 useInstantForLocalDateTime 选项，只有 useJava8LocalDateTimeEct

目前的需求是需要将  DateTime 数据库类型的字段， 转换为 Instant

**Comment by gejun123456** [comment]
好像没弄，可以定制列里面改下java类型，之后弄弄。
