### ISSUE TITLE
方法名生成xml提示xml file no found error

### ISSUE THREAD

**Issue by cddon** [gejun123456/MyBatisCodeHelper-Pro#373]
错误提示详情：can't find xml file for namespace DirectoryTreeMapper, you can generate it by alt+enter on your mapper interface name
idea版本：2018.3.6
插件版本：2.1（换成2.5也不行）

**Comment by gejun123456** [comment]
是不是装了其他mybatis插件   参考这个https://gejun123456.github.io/MyBatisCodeHelper-Pro/#/install?id=%E5%AE%89%E8%A3%85

**Comment by cddon** [comment]
> 是不是装了其他mybatis插件 参考这个https://gejun123456.github.io/MyBatisCodeHelper-Pro/#/install?id=%E5%AE%89%E8%A3%85

是的，删了我的freeMybatisPlugin就好了，感觉这个可以列入文档的常见问题中..

**Comment by gejun123456** [comment]
好的，谢谢
