### ISSUE TITLE
在数据库表 字段数据类型改变时候, 定制列里面的数据类型没有同步更改,

### ISSUE THREAD

**Issue by QingMings** [gejun123456/MyBatisCodeHelper-Pro#384]
![image](https://user-images.githubusercontent.com/22107668/57343801-5bff0f80-7177-11e9-8780-5fe04cd5a82f.png)

首先数据表里有一些字段是`varchar `,对应java里的`String`
然后我生成了实体,
然后改变字段数据类型为 `decimal` , 这时候回到IDEA里 刷新,IDEA里已经变过来了,
然后重新生成实体的时候,我发现实体数据类型没有变,然后看到是因为`定制列`这里没有更新过来,
尝试刷新,重启IDEA ,都无效,

**Comment by gejun123456** [comment]
好的，我试下，谢谢反馈

**Comment by gejun123456** [comment]
我试了下没发现问题，可以加我qq 1098632410 么，我来远程看下

**Comment by gejun123456** [comment]
这个问题能复现么

**Comment by gejun123456** [comment]
我复现了这个，是使用了useActualColumnName吗

我已经修复了，可以加 qq群 542735979 下载

**Comment by gejun123456** [comment]
#412 
#411

**Comment by QingMings** [comment]
好的，
