### ISSUE TITLE
数据库生成crud 时 选择基类后 生成实体需去除基类中的属性

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/MyBatisCodeHelper-Pro#387]
如果实体类 选了基类 生成的实体 需要去掉 基类中的属性

**Comment by xiejx618** [comment]
这个问题解决了吗

**Comment by gejun123456** [comment]
还没，过几天弄弄

**Comment by gejun123456** [comment]
2.7.4 已支持

**Comment by xiejx618** [comment]
public class ExtEo extends BaseEo {
    private Long tenantId;

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }
}

**Comment by gejun123456** [comment]
已经解决了，2.7.4版本及以上  有问题可以加我qq 1098632410 看看

**Comment by xiejx618** [comment]
public class BaseEo implements Serializable {
    private Date createTime;
    private Date updateTime;
    private String createPerson;
    private String updatePerson;
    private Integer dr;
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getCreatePerson() {
        return createPerson;
    }

    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    public String getUpdatePerson() {
        return updatePerson;
    }

    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }

    public Integer getDr() {
        return dr;
    }

    public void setDr(Integer dr) {
        this.dr = dr;
    }
}



public class ExtEo extends BaseEo {
    private Long tenantId;

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }
}

CREATE TABLE `user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` varchar(38) NOT NULL DEFAULT '' COMMENT '密码',
  `age` int(11) NOT NULL DEFAULT '0' COMMENT '年龄',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0',
  `dr` tinyint(2) NOT NULL DEFAULT '0',
  `create_person` varchar(50) NOT NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT '1000-01-01 00:00:00',
  `update_person` varchar(50) NOT NULL DEFAULT '',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


选择ExtEo作为生成实体类的基类,MyBatisCodeHelper-Pro2.7.6测试结果如下，也就是父类的父类的字段没有去重
package org.exam.demo.domain;

import java.util.Date;

public class User extends ExtEo {
    private Long id;

    /**
    * 用户名
    */
    private String name;

    /**
    * 密码
    */
    private String password;

    /**
    * 年龄
    */
    private Integer age;

    private Integer dr;

    private String createPerson;

    private Date createTime;

    private String updatePerson;

    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getDr() {
        return dr;
    }

    public void setDr(Integer dr) {
        this.dr = dr;
    }

    public String getCreatePerson() {
        return createPerson;
    }

    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getUpdatePerson() {
        return updatePerson;
    }

    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}

**Comment by gejun123456** [comment]
好滴，父类的父类我看看

xiejx618 <notifications@github.com>于2019年11月3日 周日上午9:54写道：

**Comment by gejun123456** [comment]
我修了下，可以试试这个 qq 群：542735979 可以下载
