### ISSUE TITLE
xml跳转问题

### ISSUE THREAD

**Issue by zyzling** [gejun123456/MyBatisCodeHelper-Pro#394]
你好，想问下，该插件只支持mapper接口和xml之间互相跳转么？不支持继承了SqlSessionDaoSupport的dao类和xml之间跳转么？在freeMybatisplugin里，在service层，选中dao的方法，按ctrl+t会弹出让你跳dao层还是直接到sql的选择。请问下，该插件有类似功能么？该插件已经很好了，我很喜欢，但是这个功能我没找到，然后又因为和freeMybatisplugin有冲突，所以二者又不能兼得，这让人很难抉择。希望大佬有空的时候回复下。谢谢。

**Comment by gejun123456** [comment]
因为 SqlSessionDaoSupport 用得很少，所以目前没有支持
想问下你们一般用 SqlSessionDaoSupport  是用来做什么
我看看这块

**Comment by zyzling** [comment]
感谢回复，SqlSessionDaoSupport 是一种原始的dao层解决方案，在类中调用xml中的sql，需要这样写：
```
public void updateUser(){
     Map<String,Object> map = new HashMap<>();
     map.put("id",1);
     map.put("name","张三");
     this.getSqlSession().update("updateUser",map);
}
```
其中"updateUser"会在xml中有一个<update id="updateUser">对应。
哦，对了，装上大佬开发的插件后，点击id是可以跳到updateUser方法的。但是在xml边上没有图标。懵逼。是我idea配置除了问题么？

**Comment by gejun123456** [comment]
你们新的代码也使用 SqlSessionDaoSupport 这个么，这个相比直接接口到xml 有啥好处么。感觉现在基本没人用了。
这边应该不会支持，抱歉。

**Comment by zyzling** [comment]
好吧。没事，感谢大佬回复。
