### ISSUE TITLE
支持mapper xml中select语句的正确结果类型

### ISSUE THREAD

**Issue by williamBoss** [gejun123456/MyBatisCodeHelper-Pro#395]
尊敬的作者，你好，希望修改了返回的结果类型，mapper文件的 resultType 可以自动修改为对应的对象路径
这个插件free Mybatis Plugin的功能

**Comment by gejun123456** [comment]
嗯，可以的，谢谢建议

**Comment by williamBoss** [comment]
感谢，感谢

**Comment by gejun123456** [comment]
群文件已经支持了，可以试试

**Comment by gejun123456** [comment]
![检测resultType和resultMap是否和返回值一致2](https://user-images.githubusercontent.com/6340473/58924371-35cc8f80-8776-11e9-9364-41288ab1f69c.gif)

**Comment by gejun123456** [comment]
2.7已解决
