### ISSUE TITLE
exampleQuery和tkmapper的冲突

### ISSUE THREAD

**Issue by hupeiD** [gejun123456/MyBatisCodeHelper-Pro#398]
exampleQuery和tkmapper同时勾选的时候，mapper.xml关于example操作的接口都无法使用，tkmapper里面已经集成了相关的接口，会有冲突

**Comment by gejun123456** [comment]
好的，我加个判断

**Comment by hupeiD** [comment]
感谢

**Comment by gejun123456** [comment]
好吧，这个忘了弄 :)

**Comment by hupeiD** [comment]
|･ω･｀)

**Comment by gejun123456** [comment]
已经添加了，可以试试

**Comment by hupeiD** [comment]
但是如果我想要同时继承tk.mapper和生成对应实体类的example来简化对Example的操作怎么办呢？是否可以在生成时对mapper的接口方法做判断，如果继承类中有相同的方法了就不在子类添加同名方法了，或者直接判断两个同时勾选的时候就不生成对应mapper接口的方法。

**Comment by gejun123456** [comment]
可以用我的那个方法名生成替换掉example操作

example的这个之后再看看



Hp <notifications@github.com>于2019年6月26日 周三上午11:39写道：

**Comment by gejun123456** [comment]
可以用方法名生成sql来替换掉example的操作

example能生成的 方法名都能生成

**Comment by hupeiD** [comment]
嗯，刚才试了，是可以的。其实主要是继承父类向上检查，感觉这样用于解决这个问题比较优雅😂
