### ISSUE TITLE
mysql的txt类型的字段，自动生成的mapper文件没有

### ISSUE THREAD

**Issue by kvkboy** [gejun123456/MyBatisCodeHelper-Pro#403]
数据库字段类型是txt的话，mapper里面的一些BaseResultMap不会生成该字段

**Comment by gejun123456** [comment]
怎么关了，txt类型是指text类型码

**Comment by kvkboy** [comment]
> 怎么关了，txt类型是指text类型码

是我的问题，你确实实现了，Mapper里面把text类型映射成了LONGVARCHAR
