### ISSUE TITLE
Test current xml tag 之后的console加上use databasename

### ISSUE THREAD

**Issue by SeluneXscd** [gejun123456/MyBatisCodeHelper-Pro#406]
Test current xml tag之后的语句，可以在首句加上use databasename吗？
每次测试都需要手动加上

**Comment by gejun123456** [comment]
可以配置idea数据库的时候 就把数据库名给填上
这样就不用每次都加了

**Comment by SeluneXscd** [comment]
请问怎么设置呢:smile:

**Comment by gejun123456** [comment]
https://gejun123456.github.io/MyBatisCodeHelper-Pro/#/configure

**Comment by SeluneXscd** [comment]
好的谢谢:smile:
