### ISSUE TITLE
生成Service后，没有添加import java.util.List;语句

### ISSUE THREAD

**Issue by hyperqing** [gejun123456/MyBatisCodeHelper-Pro#408]
![image](https://user-images.githubusercontent.com/8706905/58849945-f000c000-86be-11e9-83a8-07dfd272c3c9.png)

![image](https://user-images.githubusercontent.com/8706905/58849966-03ac2680-86bf-11e9-9a18-3909f36ec8ac.png)

![image](https://user-images.githubusercontent.com/8706905/58849993-276f6c80-86bf-11e9-9d1f-e085b17a6fe7.png)

**Comment by gejun123456** [comment]
好的，谢谢反馈

**Comment by gejun123456** [comment]
2.7已解决
