### ISSUE TITLE
多模块的问题

### ISSUE THREAD

**Issue by 1397649957** [gejun123456/MyBatisCodeHelper-Pro#414]
idea 多模块项目下，如果多个模块出现相同的mapper 和 xml，会乱跳，a模块的aDao会跳到b模块的aMapper.xml

**Comment by gejun123456** [comment]
多个模块之间有依赖关系吗， 另外两个模块的包名+类名 完全一样么

**Comment by gejun123456** [comment]
插件的版本是多少哈

**Comment by gejun123456** [comment]
建议两个模块 区分下包名。
