### ISSUE TITLE
IntelliJ IDEA 2019.2 EAP安装2.7.0后问题一堆

### ISSUE THREAD

**Issue by mostcool** [gejun123456/MyBatisCodeHelper-Pro#427]
IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5281.24, built on June 19, 2019
IntelliJ IDEA EAP User
Expiration date: July 19, 2019
Runtime version: 11.0.3+12-b304.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1502M
Cores: 4

安装后，IDEA智能提示失效，Git Commit 输入文字时，一次只能输一个中文汉字。可能还有其它问题，暂时未发现。

**Comment by gejun123456** [comment]
可以加qq群542735979
早上修了2019.2 的一个bug 
有其他问题可以反馈

git commit只能输入一个中文汉字这个应该是idea的bug吧，eap版本估计不太稳定。

**Comment by mostcool** [comment]
> 可以加qq群542735979
> 早上修了2019.2 的一个bug
> 有其他问题可以反馈
> 
> git commit只能输入一个中文汉字这个应该是idea的bug吧，eap版本估计不太稳定。

把你这个插件降为2.6.1就可以正常输入中文了。不确定是不是你这个插件引起的问题。

**Comment by gejun123456** [comment]
wow 我也不知道，可以先下群文件的新版本看看有没有问题

**Comment by mostcool** [comment]
> wow 我也不知道，可以先下群文件的新版本看看有没有问题

用你群里snapshot版本，我说的两个问题都解决了。赞！

**Comment by gejun123456** [comment]
哈哈，虽然我还是不知道git中文那个和我插件有啥关系，解决了就好 :)
