### ISSUE TITLE
优化where语句

### ISSUE THREAD

**Issue by leyou240** [gejun123456/MyBatisCodeHelper-Pro#440]
对于where后所有的字段都有test的情况，使用<where>标签
例如如下代码
`        select
        <include refid="Base_Column_List"/>
        from user
        where 1=1
        <if test="minTime != null">
            and `time` <![CDATA[>]]> #{minTime,jdbcType=TIMESTAMP}
        </if>`

可优化成
`        select
        <include refid="Base_Column_List"/>
        from user
        <where>
            <if test="minTime != null">
                 `time` <![CDATA[>]]> #{minTime,jdbcType=TIMESTAMP}
            </if>
        </where>`

公司的dba要求，不能使用where 1=1。这样生成了之后，还需要手动去修改

**Comment by gejun123456** [comment]
可以的 我弄弄

**Comment by gejun123456** [comment]
群文件已支持

**Comment by kings1990** [comment]
delete、update 在where后只带一个条件if条件的需要警告,不然sql不安全

**Comment by gejun123456** [comment]
的确. 但是怎么警告呢，加注释么

**Comment by kings1990** [comment]
> 的确. 但是怎么警告呢，加注释么


- 针对带if条件的情况
	- 如果where后有多个条件
		* 如果是update、delete那就得警告了,如果是select那就没关系
	- 如果where后有多个条件
		* 如果全勾 用 <where>标签包起来  第一个<if>不加and/or(加了好像编辑器会觉得语法问题)
		* 如果只勾了一个及以上(不包含全勾) 用where而不是`<where>`,没有if的放前面 有if的放后面,如where a=#{a} 后面是if条件语句
		* 如果一个没勾,警告之

警告处理方式: 如果出现不安全的情况,就不让点击确定,必须得勾一个不带if的条件,然后再弹出框里面说明一下

**Comment by kings1990** [comment]
> 的确. 但是怎么警告呢，加注释么

- 针对带if条件的情况
	- 如果where后有多个条件
		* 如果是update、delete那就得警告了,如果是select那就没关系
	- 如果where后有多个条件
		* 如果全勾 用 <where>标签包起来  第一个<if>不加and/or(加了好像编辑器会觉得语法问题)
		* 如果只勾了一个及以上(不包含全勾) 用where而不是`<where>`,没有if的放前面 有if的放后面,如where a=#{a} 后面是if条件语句
		* 如果一个没勾,警告之

警告处理方式: 如果出现不安全的情况,就不让点击确定,必须得勾一个不带if的条件,然后再弹出框里面说明一下

**Comment by gejun123456** [comment]
谢谢解释
where后面有1个条件 -> 弄个警告
如果where后有多个条件
如果全勾 用 标签包起来 第一个不加and/or(加了好像编辑器会觉得语法问题)  -> 编辑器不会有问题的，插件适配了这个
只要勾了一个 我觉得就可以用where标签，用where标签也没有啥影响 方便以后加if test.
如果一个没勾 我觉得没必要警告
