### ISSUE TITLE
dao和mapper问题。

### ISSUE THREAD

**Issue by M-make** [gejun123456/MyBatisCodeHelper-Pro#442]
![image](https://user-images.githubusercontent.com/35563513/60311636-b43ddb00-998a-11e9-90ae-53ab923e2d35.png)
![image](https://user-images.githubusercontent.com/35563513/60311639-b7d16200-998a-11e9-9e62-4dda1b801719.png)
![image](https://user-images.githubusercontent.com/35563513/60311644-bbfd7f80-998a-11e9-98b3-6213bb9775af.png)
![image](https://user-images.githubusercontent.com/35563513/60311660-d172a980-998a-11e9-96ff-b5b8b26fc1e3.png)
这个you有啥问题吗，为什么会有这种提示
![image](https://user-images.githubusercontent.com/35563513/60311682-e8b19700-998a-11e9-99c6-3c293d370c0d.png)

**Comment by gejun123456** [comment]
看起来没问题

**Comment by gejun123456** [comment]
这个是检测接口的返回值和resultMap的类型是否一致
你这个看起来配置是没有问题的，我检查下插件代码

**Comment by gejun123456** [comment]
我在本地照你这种试了下，没发现问题，  这个问题可以重现么，idea版本是多少。

**Comment by gejun123456** [comment]
有没有装其他的mybatis插件  如 mybatisx mybatisplugin freeMybatisPlugin 这些 插件会有冲突

**Comment by M-make** [comment]
好的，我本地检查下

**Comment by M-make** [comment]
我先本地检查下，是否是别的因素导致的

**Comment by gejun123456** [comment]
插件冲突应该不会引起这个问题 可以invalidatcache restart试下

**Comment by gejun123456** [comment]
问题解决了么

**Comment by gejun123456** [comment]
找到原因，可以在群文件下在2.7.2版本

**Comment by M-make** [comment]
好的，那个github上为啥不发布一下release
