### ISSUE TITLE
需求：注解语句转xml

### ISSUE THREAD

**Issue by HiJackXD** [gejun123456/MyBatisCodeHelper-Pro#446]
在xml里写语句还是不太方便，希望能增加“将注解种的查询语句自动转为xml查询语句“的功能。

**Comment by gejun123456** [comment]
一键改你的代码么，把你写好的java接口上面的sql 移到xml里面么

**Comment by gejun123456** [comment]
这种是可以弄的，插件还是建议直接在xml中sql，各种补全和代码生成在xml 中使用最方便

**Comment by HiJackXD** [comment]
嗯嗯 想了的确没有必要为了这种用的少的功能单独再加按钮了
