### ISSUE TITLE
跳转不对，有时候点击图标回跳到Test的xml里

### ISSUE THREAD

**Issue by TanqiZhou** [gejun123456/MyBatisCodeHelper-Pro#46]
有时候点击图标回跳到Test的xml里，而应该跳到main里的resources，有时候新文件会这样，不知道为什么

**Comment by gejun123456** [comment]
有例子可以看看么，是不是Test的namespace和dao一样所以导致跳转有问题，我等下在自己本地试下

**Comment by gejun123456** [comment]
如果test中的namespace和resource中xml 的namespace一样，有可能会跳转到test的xml中，我会修复下

**Comment by TanqiZhou** [comment]
是的，最好加个选择;谢谢了，难道有你那样积极的开发者。




------------------ 原始邮件 ------------------
发件人: "葛俊";<notifications@github.com>;
发送时间: 2017年10月19日(星期四) 凌晨0:04
收件人: "gejun123456/MyBatisCodeHelper-Pro"<MyBatisCodeHelper-Pro@noreply.github.com>;
抄送: "《带你去旅游》"<1158869638@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [gejun123456/MyBatisCodeHelper-Pro] 跳转不对，有时候点击图标回跳到Test的xml里 (#46)




如果test中的namespace和resource中xml 的namespace一样，有可能会跳转到test的xml中，我会修复下

**Comment by gejun123456** [comment]
1,7.1版本将修复
