### ISSUE TITLE
一个解析bug

### ISSUE THREAD

**Issue by zlsq** [gejun123456/MyBatisCodeHelper-Pro#467]
在xml中编写如下sql的时候会解析错误
```sql
insert into 
<choose>
    <when test="booleanValue">
      a
    </when>
    <otherwise>
      b
    </otherwise>
</choose>
(id,name) values ('1','张三')
```

**Comment by gejun123456** [comment]
嗯，可以通过2.7.1 版本 @ignore注释来解决 
https://gejun123456.github.io/MyBatisCodeHelper-Pro/#/typeSafe?id=%E5%BD%93%E4%BD%BF%E7%94%A8if-test%E6%97%B6-%E5%8F%AF%E8%83%BD%E5%8F%AA%E6%9C%89%E9%83%A8%E5%88%86%E6%9D%A1%E4%BB%B6%E6%88%90%E7%AB%8B-choose-when-%E5%88%99%E5%8F%AA%E6%9C%89%E4%B8%80%E4%B8%AA%E6%9D%A1%E4%BB%B6%E6%88%90%E7%AB%8B-%E6%8F%92%E4%BB%B6%E5%BC%95%E5%85%A5%E4%BA%86-ignoresql-%E6%B3%A8%E9%87%8A%EF%BC%8C%E5%A6%82%E6%9E%9C%E9%9C%80%E8%A6%81if-test-%E6%88%96choose-when-%E4%B8%8D%E6%88%90%E7%AB%8B%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E8%AF%A5%E6%B3%A8%E9%87%8A%EF%BC%8C%E6%A3%80%E6%B5%8Bsql%E6%98%AF%E5%90%A6%E6%AD%A3%E7%A1%AE%E5%92%8C%E4%BB%A3%E7%A0%81%E6%8F%90%E7%A4%BA

**Comment by zlsq** [comment]
好的，已经解决了，感谢回复。
