### ISSUE TITLE
插件无法在现有项目下提示生成方法

### ISSUE THREAD

**Issue by ilumer** [gejun123456/MyBatisCodeHelper-Pro#480]
在已经存在interface mode mapper的项目中，如果想要在interface 中得到类似与jpa一样的体验只能通过插件覆盖(通过Mybatis generator)原本的方法，还有其他的方法来实现吗(加入QQ群失败，只能通过这个方法来获得支持 抱歉)。

**Comment by gejun123456** [comment]
是指方法名生成不能用吗 可以看下报错吗

**Comment by gejun123456** [comment]
可以加我qq 1098632410 我来看看

**Comment by ilumer** [comment]
在dao层以及存在的interface中是没法获得补全 以及自己生成方法的提示的，需要根据table 生成重新一次，这样就可以获取提示了，请问应该如何去处理这样的情况(没有发现错误信息，只是无法获得补全)。

**Comment by gejun123456** [comment]
自动补全需要你的接口里面有一个insert或save方法 可以看下接口的内容么

**Comment by ilumer** [comment]
因为一些原因我暂时无法给出完全一致的代码，我修改了部分地方 希望不影响你的判断
```model
    //数据库模型 BO为命名要求
    public class ABO{
        xxxxx
    }

    public class ADAO{
        //现在存在的方法
        long insertasdasd(ADO ado,xxxx)
    }
```
如果我希望获得提示 需要在这个dao层和mapper层做哪些修改，谢谢。

**Comment by gejun123456** [comment]
insert 这个方法改成一个参数试试 insert(ADO ado) 这种

**Comment by ilumer** [comment]
解决了问题 谢谢
