### ISSUE TITLE
xml接收带泛型的JavaObject参数时，无法识别泛型对象中的属性

### ISSUE THREAD

**Issue by yiyingcanfeng** [gejun123456/MyBatisCodeHelper-Pro#496]
![Snipaste_2019-09-10_14-46-02](https://user-images.githubusercontent.com/39869232/64590952-475bae00-d3db-11e9-9830-ef951f98e475.png)
![Snipaste_2019-09-10_14-46-10](https://user-images.githubusercontent.com/39869232/64590971-53477000-d3db-11e9-8635-6323adade667.png)
![Snipaste_2019-09-10_14-46-23](https://user-images.githubusercontent.com/39869232/64590977-58a4ba80-d3db-11e9-928b-2c37f6928035.png)
![Snipaste_2019-09-10_14-46-36](https://user-images.githubusercontent.com/39869232/64590983-5b9fab00-d3db-11e9-930b-e50371feba89.png)

**Comment by gejun123456** [comment]
好的， 谢谢反馈，我看下

**Comment by gejun123456** [comment]
的确有这个问题，我看了下加上param注解的话 倒是可以识别， 我修修

**Comment by yiyingcanfeng** [comment]
> 的确有这个问题，我看了下加上param注解的话 倒是可以识别， 我修修

好的，谢谢

**Comment by gejun123456** [comment]
修复好了，群文件可以下载
