### ISSUE TITLE
生成的文件直接把原来加上去的一些方法覆盖了，可以设置不覆盖吗

### ISSUE THREAD

**Issue by lvior** [gejun123456/MyBatisCodeHelper-Pro#50]

**Comment by lvior** [comment]
dao层mapper接口的方法,不是xml

**Comment by gejun123456** [comment]
你是指通过java类生成对应dao的时候覆盖了吗，正常不会覆盖的，你使用的版本是多少哈？

**Comment by lvior** [comment]
jdk1.7.0_80这个版本的

**Comment by lvior** [comment]
不是通过java类，是通过mybatis genertor的配置文件生成的

**Comment by gejun123456** [comment]
好的，我看下，谢谢反馈

**Comment by gejun123456** [comment]
mybatis generator 源码 目前只支持覆盖，https://github.com/mybatis/generator/issues/269
看了 eclispe上的插件是支持这个功能的，我先试试改改，应该可以支持的。

**Comment by gejun123456** [comment]
下个版本支持，谢谢建议。
