### ISSUE TITLE
MybaitsCodeHelper-obfuss.jar 中有不明文件

### ISSUE THREAD

**Issue by lzimd** [gejun123456/MyBatisCodeHelper-Pro#502]
如图：
![图片](https://user-images.githubusercontent.com/29934671/65223660-3d7d2d80-daf4-11e9-9c91-6f9353fab3cc.png)

版本为 2.7.5
其中 libhello.dll 不知道是什么，且在 Intellij IDEA 运行时会在临时目录出现

**Comment by gejun123456** [comment]
有用的，你为啥关心这个。

**Comment by lzimd** [comment]
我也会加载jar包里的so/dll，会在TEMP目录释放，看见个libhello.dllXXXXXX，查看是idea64.exe进程占用，比较好奇

如果方便的话，可以换个名字吗

**Comment by gejun123456** [comment]
嗯，后面会干掉这个的
