### ISSUE TITLE
mybatis-plus 自定义语句 ${ew.customSqlSegment} 标红，希望兼容一下

### ISSUE THREAD

**Issue by link2fun** [gejun123456/MyBatisCodeHelper-Pro#508]
![](https://img.next2you.cn:8443/2019/10/20191008101000315-3420.png)

版本：2.7.5

**Comment by gejun123456** [comment]
https://github.com/gejun123456/MyBatisCodeHelper-Pro/issues/507 是和这个问题一样吗，群文件已经支持了

**Comment by link2fun** [comment]
> #507 是和这个问题一样吗，群文件已经支持了

thx，我去试一下
