### ISSUE TITLE
xml不能被识别为spring的bean

### ISSUE THREAD

**Issue by WakelessDragon** [gejun123456/MyBatisCodeHelper-Pro#52]
![image](https://user-images.githubusercontent.com/6255739/33308817-03948e06-d457-11e7-8c05-52aa5de97ff7.png)

**Comment by gejun123456** [comment]
这个和我的插件有联系么，感觉应该是idea spring插件的问题，不支持识别mybatis注册的bean。

**Comment by gejun123456** [comment]
看了下 http://www.jetbrains.org/intellij/sdk/docs/reference_guide/frameworks_and_external_apis/spring_api.html

**Comment by gejun123456** [comment]
应该可以支持，我试试。
