### ISSUE TITLE
2.7.6版本 model生成的@ApiModel(value = "a-b-c-d")路径符号错误

### ISSUE THREAD

**Issue by moyutech** [gejun123456/MyBatisCodeHelper-Pro#520]
2.7.6版本 
config区域勾选swaggerAnnotation时，
生成的model生成的@ApiModel(value = "a-b-c-d")出错
在2.7.5版本中这部分是正确的 @ApiModel(value = "a.b.c.d")

**Comment by gejun123456** [comment]
swagger使用的啥版本 之前有用户提出用 . 有问题就替换成了-

**Comment by moyutech** [comment]
springfox-swagger2 的版本是2.9.2
明白了，使用 . 会导致springfox-swagger-ui中的model无法点击，
确实应该使用 -
