### ISSUE TITLE
在IDEA中，projectConfig 的 typeAliasPackages该如何配置才能加载到别名

### ISSUE THREAD

**Issue by MixuanS** [gejun123456/MyBatisCodeHelper-Pro#528]
在IDEA中，projectConfig 的 typeAliasPackages该如何配置才能加载到别名

**Comment by gejun123456** [comment]
直接配置就行了，不过目前不支持*号，可以自己把*号展开下为多个 用分号分隔

**Comment by gejun123456** [comment]
\* 号

**Comment by MixuanS** [comment]
我试过在输入框里填入我mybatis-config文件绝对路径和相对路径，但是发现配置文件都没有生效。因为引用别名的地方还是报错。那么在输入框里该填入的内容是什么

**Comment by gejun123456** [comment]
直接填你的typealias包名配置 而不是mybatis config文件的地址

**Comment by gejun123456** [comment]
![支持typeAlias配置](https://user-images.githubusercontent.com/6340473/67729490-42ef6100-fa2c-11e9-8f2a-dc2cd207be60.gif)

**Comment by MixuanS** [comment]
嗯嗯，搞定
