### ISSUE TITLE
请问selectByAll可以增加条件吗

### ISSUE THREAD

**Issue by superxxl** [gejun123456/MyBatisCodeHelper-Pro#541]
有需求会是，传入对象查询，但是有些对象有固定条件
比如说，（不跨表查）我现在要查询没有分配过角色的用户，而我还要根据用户信息去筛选，以后还会增加筛选条件，byAll不能增加条件那么查询条件会非常长，而且不方便

**Comment by gejun123456** [comment]
有例子可以看看么，这种可以通过方法名来生成么

**Comment by gejun123456** [comment]
以后会支持 findByAllExceptDateBetween这种语法 看看能不能实现

**Comment by superxxl** [comment]
就一个简单的例子，我条件查询列表的时候，我其中一个字段要模糊查询，或者说我要根据创建时间排序，如果能支持selectByAllAndxxxOrderByxxx就方便很多，基本就是全能了，不过看起来命名不太好。。。

**Comment by gejun123456** [comment]
可以支持的，selectByAllExceptXXXLikeOrderByxxx 我来弄弄

**Comment by gejun123456** [comment]
群文件已支持

**Comment by superxxl** [comment]
大佬真好
