### ISSUE TITLE
Base_Column_List元素内容可以自动加入"表名."吗

### ISSUE THREAD

**Issue by woohanhan** [gejun123456/MyBatisCodeHelper-Pro#547]
`  <sql id="Base_Column_List">
    
    ID
  </sql>`
可以自动加入表名前缀吗？例如：
`  <sql id="Base_Column_List">
    
    table.ID
  </sql>`

**Comment by gejun123456** [comment]
配置里面有个addSchemaName 配置上就有了

**Comment by woohanhan** [comment]
thanks

**Comment by gejun123456** [comment]
我弄错了，生成join不是一个，可以通过在表上右键 generate all column sql 生成
![generateAllColumnSql](https://user-images.githubusercontent.com/6340473/70681336-0626b300-1cd6-11ea-89f0-230b900bc45d.gif)
