### ISSUE TITLE
mysql json字段映射resultMap问题

### ISSUE THREAD

**Issue by YiuTerran** [gejun123456/MyBatisCodeHelper-Pro#552]
如果使用mybatis plus的话，可以自动加上`typeHandler="com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler"`

然后JdbcType应该是VARCHAR，而不是OTHER吧，用OTHER会直接启动报错

**Comment by gejun123456** [comment]
定制列里面可以配置的

**Comment by gejun123456** [comment]
json类型我看下

**Comment by gejun123456** [comment]
群文件已支持 2.7.8版本
