### ISSUE TITLE
插件mapper.xml中总是提示unable to resolve table

### ISSUE THREAD

**Issue by lantyu** [gejun123456/MyBatisCodeHelper-Pro#558]
之前一直可以没问题
直到更新到最新2.7.8 193这个版本后(现在手动更新到群里发的2.7.9), mapper.xml仍然无法识别表,所以所有的列属性无法进行智能提示

关于数据源,使用idea database那个已经配置完成,并且可以通过这个使用mybatiscodehelper pro 进行generator 生成类和代码,都正常,所以数据源应该链接正确的.

**Comment by gejun123456** [comment]
看文档配置数据库那节，照着配置下，记得dialect需要配置下

之前也有人碰到了这个问题，配置下dialect就好了

**Comment by lantyu** [comment]
确实可以 希望葛大 把这个加到常见问题里面 感谢

**Comment by gejun123456** [comment]
可以的 谢谢建议

li_zongxing <notifications@github.com>于2020年2月22日 周六下午3:44写道：
