### ISSUE TITLE
建议去掉<!--@mbg.generated-->或者增加配置选项可以选择去掉

### ISSUE THREAD

**Issue by tawoli** [gejun123456/MyBatisCodeHelper-Pro#561]
建议增加配置项 可以配置生成的xml中不生成

**Comment by gejun123456** [comment]
有配置可以去掉的，不过mbg generated  合并代码的时候有用的。
https://gejun123456.github.io/MyBatisCodeHelper-Pro/#/question?id=%e6%88%91%e4%b8%8d%e6%83%b3%e8%a6%81xml%e7%9a%84%e6%b3%a8%e9%87%8a%e6%80%8e%e4%b9%88%e5%a4%84%e7%90%86
