### ISSUE TITLE
mysql tinyint映射为byte可选择转换为integer

### ISSUE THREAD

**Issue by tawoli** [gejun123456/MyBatisCodeHelper-Pro#566]
考虑到byte在java代码里面使用不便，通常tinyint java使用integer进行映射，mybatiscodehelper默认为byte 且不支持选择

**Comment by gejun123456** [comment]
idea mybatisCodehelper里面有个设置的useIntergerInsteadOfShortAndByte
勾一下就行罗

**Comment by tawoli** [comment]
> idea mybatisCodehelper里面有个设置的useIntergerInsteadOfShortAndByte
> 勾一下就行罗

谢谢
