### ISSUE TITLE
建议增加tinyint(1)转换Integer的选项

### ISSUE THREAD

**Issue by tawoli** [gejun123456/MyBatisCodeHelper-Pro#570]
如题

**Comment by tawoli** [comment]
讲一下原因，最初设计是tinyint(1)，后面由于业务变动，无视宽度，增加了其他的数字

**Comment by gejun123456** [comment]
测试数据库可以改成tinyint(4),然后设置里面勾下useIntegerInsteadOfByteAndShort就行啦

**Comment by tawoli** [comment]
> 测试数据库可以改成tinyint(4),然后设置里面勾下useIntegerInsteadOfByteAndShort就行啦

原则上可以，目前是在正式环境运行，是否有其他手段可以改动这个生成类型
