### ISSUE TITLE
xml 中拼接sql 检验报错，更改方言无效

### ISSUE THREAD

**Issue by mingyujiao** [gejun123456/MyBatisCodeHelper-Pro#586]
![image](https://user-images.githubusercontent.com/49345287/82729471-6eb89800-9d2a-11ea-846f-6a6d85db6a2b.png)

**Comment by gejun123456** [comment]
$上alt enter 添加一个注释 看文档常见问题 https://gejun123456.github.io/MyBatisCodeHelper-Pro/#/question?id=%e4%bd%bf%e7%94%a8%e7%9a%84sql%e4%bc%9a%e6%a0%87%e7%ba%a2
