### ISSUE TITLE
生成代码时，选择定制列，Java Type 不支持自定义的枚举类

### ISSUE THREAD

**Issue by linjunzhu** [gejun123456/MyBatisCodeHelper-Pro#588]
有些属性是  TINYINT 类型，一般都会用自定义的枚举类来替代成：

MsgStatus
PayStatus

但是 Java Type 列手动输入枚举类的全地址，点击生成代码，依旧生成了 Byte 类型

**Comment by linjunzhu** [comment]
若手动改掉 Model 类的属性类型为自定义枚举类，以后新增字段时，再次生成后，手动改的自定义枚举类属性又会被覆盖了

**Comment by linjunzhu** [comment]
又测试了一下：

在定制类中改为自定义的枚举类后， 需要指定对应的 type handler 才能生效

**Comment by gejun123456** [comment]
Java Type 列手动输入枚举类的全地址 后点一下enter 在生成下看看。

**Comment by gejun123456** [comment]
嗯，typeHandler也可以配置下。

**Comment by linjunzhu** [comment]
@gejun123456 手动输入枚举类的全地址，点击 enter 生成，无法生效。

指定了对应的 type handeler 才生效了
