### ISSUE TITLE
自动生成resultMap字段对应错误

### ISSUE THREAD

**Issue by mingyujiao** [gejun123456/MyBatisCodeHelper-Pro#590]
<resultMap id="contSubcontractApprovalDto" type="工程路径">
      <id column="id" property="id"/>
    <result column="id" property="bId"/>
    <result column="act_task_key" property="actTaskKey"/>
    <result column="id" property="pId"/>
    <result column="con_code" property="conCode"/>
    <result column="con_name" property="conName"/>
    <result column="con_modality" property="conModality"/>
    <result column="con_type" property="conType"/>
    <result column="other_con_type" property="otherConType"/>
    <result column="con_start_date" property="conStartDate"/>
    <result column="con_end_date" property="conEndDate"/>
    <result column="con_signing_date" property="conSigningDate"/>
    <result column="con_pay_way" property="conPayWay"/>
    <result column="other_pay_way" property="otherPayWay"/>
    <result column="con_total" property="conTotal"/>
    <result column="con_partya" property="conPartya"/>
    <result column="signatorya" property="signatorya"/>
    <result column="con_partyb" property="conPartyb"/>
    <result column="signatoryb" property="signatoryb"/>
    <result column="is_exceed_total" property="isExceedTotal"/>
    <result column="is_exceed" property="isExceed"/>
    <result column="is_run_procedure" property="isRunProcedure"/>
    <result column="remarks" property="remarks"/>
    <result column="con_pay_standard" property="conPayStandard"/>
    <result column="con_status" property="conStatus"/>
    <result column="approval_status" property="approvalStatus"/>
    <result column="sign" property="sign"/>
    <result column="sign_time" property="signTime"/>
    <result column="propose" property="propose"/>
    <result column="result" property="result"/>
    <result column="createtime" property="createtime"/>
    <result column="updatetime" property="updatetime"/>
    <result column="createuser" property="createuser"/>
    <result column="updateuser" property="updateuser"/>
    <result column="datastatus" property="datastatus"/>
    <result column="propose" property="proName"/>
    <result column="propose" property="proSubCompany"/>
    <result column="result" property="maxResultCount"/>
    <result column="sign" property="skipCount"/>
    <result column="remarks" property="searchKey"/>
    <result column="sign" property="sorting"/>
    <result column="id" property="filters"/></resultMap>

    <select id="abc" parameterType="map" resultMap="contSubcontractApprovalDto">
        select t.id, b_id, act_task_key, p_id, con_code, con_name,
        con_modality, con_type, other_con_type, con_start_date, con_end_date,
         con_signing_date, con_pay_way, other_pay_way, con_total, con_partya, signatorya,
          con_partyb, signatoryb, is_exceed_total, is_exceed, is_run_procedure,
          remarks, con_pay_standard, con_status, approval_status, sign, sign_time,
          propose, result, createtime, updatetime, createuser, updateuser, datastatus
          from t_cont_subcontract_approval t
    </select>

**Comment by gejun123456** [comment]
在匹配字段的时候应该先去掉 下划线再匹配

**Comment by gejun123456** [comment]
一个column匹配多次时 应该给个提示 warn

**Comment by gejun123456** [comment]
column要优化提示 先提示没有匹配过的字段
