### ISSUE TITLE
自动生成statement语句时,resultType类型优化

### ISSUE THREAD

**Issue by M1NGc** [gejun123456/MyBatisCodeHelper-Pro#592]
这是mapper接口声明返回值为List<Map<String,Object>> 
![image](https://user-images.githubusercontent.com/26264126/83234103-592bee00-a1c2-11ea-991a-da8f8a4aa7d7.png)
自动生成select statement时xml的resulttype错误
![image](https://user-images.githubusercontent.com/26264126/83234221-86789c00-a1c2-11ea-8e80-a2cf2e2b09d5.png)

resultType应该为java.util.Map或者map 而不是java.util.Map<java.lang.String,java.lang.Object>

**Comment by gejun123456** [comment]
是的，我加个兼容
