### ISSUE TITLE
mybatis xml 美化之后自动添加空行

### ISSUE THREAD

**Issue by bradley-wang** [gejun123456/MyBatisCodeHelper-Pro#596]
美化前：
```xml
 <delete id="xxx">
        DELETE FROM xxx
        WHERE xx = #{xx}
 </delete>
```
美化后:
```xml
<delete id="xxx">

        DELETE FROM xxx
        WHERE xxx = #{xx}

</delete>
```
这个问题很严重，影响很大，望解决。

**Comment by bradley-wang** [comment]
而且每次美化之后都自动添加空行

**Comment by gejun123456** [comment]
看文档代码格式化那节 应该是sql dialect没配置导致的

**Comment by bradley-wang** [comment]
> 看文档代码格式化那节 应该是sql dialect没配置导致的

已解决，谢谢

**Comment by authub** [comment]
> 
> 
> > 看文档代码格式化那节 应该是sql dialect没配置导致的
> 
> 已解决，谢谢

请问下怎么解决的

**Comment by gejun123456** [comment]
> > > 看文档代码格式化那节 应该是sql dialect没配置导致的
> > 
> > 
> > 已解决，谢谢
> 
> 请问下怎么解决的

https://gejun123456.github.io/MyBatisCodeHelper-Pro/#/formatter
