### ISSUE TITLE
2.8.2版本在idea 2020.1.2中生成sql格式错误

### ISSUE THREAD

**Issue by wayne0332** [gejun123456/MyBatisCodeHelper-Pro#599]
如题,通过在dao里自动生成对应的xml方法时,格式错误.
![image](https://user-images.githubusercontent.com/5112427/85359213-3930e580-b548-11ea-90e0-04d6cd6550a0.png)

**Comment by gejun123456** [comment]
嗯，升级下到2.8.2-fix2 版本看看
