### ISSUE TITLE
IDEA同时打开两个project，使用不同数据源，其中一个无法正常使用

### ISSUE THREAD

**Issue by TheDawnWind** [gejun123456/MyBatisCodeHelper-Pro#612]

**Comment by gejun123456** [comment]
无法使用是指？加我qq 1098632410 来看看

**Comment by TheDawnWind** [comment]
我现在一共开了三个project，第一个原本是用不了的（无法正常检验数据库表和字段来源），后面我把项目关闭，同时删除了idea的缓存文件，重新载入项目就ok了



 
发件人： 葛俊
发送时间： 2020-08-04 22:14
收件人： gejun123456/MyBatisCodeHelper-Pro
抄送： Wind; Author
主题： Re: [gejun123456/MyBatisCodeHelper-Pro] IDEA同时打开两个project，使用不同数据源，其中一个无法正常使用 (#612)
无法使用是指？加我qq 1098632410 来看看
