### ISSUE TITLE
ORDER BY 语句后面用 <choose> <when> <otherwise> 标签报错

### ISSUE THREAD

**Issue by flymianmian** [gejun123456/MyBatisCodeHelper-Pro#615]
![image](https://user-images.githubusercontent.com/6081897/89261578-e4ad7980-d660-11ea-9547-29c41ff257fc.png)

**Comment by flymianmian** [comment]
插件版本是 2.8.2-fix-2-183-202

**Comment by gejun123456** [comment]
看文档sql标红那节，加个ignore注释就可以了https://gejun123456.github.io/MyBatisCodeHelper-Pro/#/sqlred
