### ISSUE TITLE
postgresql没有表名，字段提示

### ISSUE THREAD

**Issue by FlyInWind1** [gejun123456/MyBatisCodeHelper-Pro#617]
没有提示，在xml中也会有字段报错
库，方言都设置过了
![20200805_210720](https://user-images.githubusercontent.com/29172747/89416454-dbef9d00-d75f-11ea-8dde-36ad80d781eb.png)

**Comment by gejun123456** [comment]
看文档配置数据库那节，应该是dialect没配置导致的

**Comment by FlyInWind1** [comment]
好了，谢谢
