### ISSUE TITLE
不能从Dao接口跳转到正确的mapper文件夹

### ISSUE THREAD

**Issue by xianzheTM** [gejun123456/MyBatisCodeHelper-Pro#618]
RT.
当项目存在多个模块时,在Dao接口上使用快捷方式:
![image](https://user-images.githubusercontent.com/25103583/89799005-83edd780-db5f-11ea-836d-8c8cc34e6d00.png)
合理的情况是在该模块中选择放mapper文件的位置,但是图中给的却是另一个模块的文件夹.而且没办法换到目标模块:
![image](https://user-images.githubusercontent.com/25103583/89799310-e3e47e00-db5f-11ea-9d2f-d23e9f90b76e.png)

**Comment by gejun123456** [comment]
![image](https://user-images.githubusercontent.com/6340473/89989146-1c48a100-dcb3-11ea-911e-ef71022f2fea.png)
我这边是在项目目录下找的，加个qq 1098632410 来看看

**Comment by gejun123456** [comment]
已修复
