### ISSUE TITLE
无法识别 sql正确与否，还是报红色，是什么问题？

### ISSUE THREAD

**Issue by lemos1235** [gejun123456/MyBatisCodeHelper-Pro#624]

**Comment by gejun123456** [comment]
来个截图看看，看文档sql标红那节https://gejun123456.github.io/MyBatisCodeHelper-Pro/#/sqlred

**Comment by lemos1235** [comment]
ok，配置了 dialets 就好了。 
![image](https://user-images.githubusercontent.com/23135552/91110450-7af91c00-e6b0-11ea-9d50-33a9c7dde963.png)
