### ISSUE TITLE
求助一个复用resultMap的问题

### ISSUE THREAD

**Issue by swansrp** [gejun123456/MyBatisCodeHelper-Pro#628]
当我用咱们的插件生成
<sql id="Base_Column_List"
<resultMap id="BaseResultMap"
其他文件进行复用引用, 运行时候有一定概率会提示尚未定义
根据我的测试结果貌似和文件名字或路径有关
像是与mybatis解析xml文件的先后有关
跪求大家一个解决方案

**Comment by gejun123456** [comment]
发一下mybatis的版本 还有是否用了其他库 如 mybatisplus，我看mybatis 的源码是不应该有这个问题的

**Comment by swansrp** [comment]
十分感谢您的回复
我是用的依赖版本是
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>2.1.0</version>
  <artifactId>mybatis</artifactId>
  <version>3.5.2</version>
  <packaging>jar</packaging>
如果您有时间 我希望能够给您发一个我出问题最小规模的项目

**Comment by swansrp** [comment]
如果您有时间帮助我的话 这是我的的问题最小规模的项目
https://github.com/swansrp/Mybatis_Puzzle

**Comment by gejun123456** [comment]
好的，谢谢，我看看

**Comment by gejun123456** [comment]
去掉tk mapper依赖后就可以跑了，可以试下

**Comment by gejun123456** [comment]
应该是tk mapper的问题，我找找原因

**Comment by swansrp** [comment]
十分感谢您的帮助 我也从这个方向探究一下原因

**Comment by swansrp** [comment]
感谢您的提示

大概是由于mybaits扫描xml在tk mapper之前
(我也忘了在哪看到过这么一句话,没在源码中找到相关的证据)
我已经找到解决 方案:
在mybatis-config.xml中添加 自定义xml文件的全局配置

<mappers>
<package name="com.mybatis.mapper"/>
</mappers>
即解决的该异常

再次感谢您的提示
