### ISSUE TITLE
建议生成实体类 使用mybatisplus的时候可以不需要设置主键属性

### ISSUE THREAD

**Issue by williamBoss** [gejun123456/MyBatisCodeHelper-Pro#629]
建议生成实体类 使用mybatisplus的时候可以不需要设置主键属性

![image](https://user-images.githubusercontent.com/24366697/91961481-ce690b00-ed3d-11ea-84cf-c8cd6519135f.png)

只需要指明主键字段就可以了
![image](https://user-images.githubusercontent.com/24366697/91961590-f48eab00-ed3d-11ea-8961-fad91d5de35e.png)

非常感谢

**Comment by gejun123456** [comment]
选 IdType.NONE 默认是这个。

**Comment by williamBoss** [comment]
好的 非常感谢
