### ISSUE TITLE
未激活版本如何一直使用

### ISSUE THREAD

**Issue by littlefisher666** [gejun123456/MyBatisCodeHelper-Pro#630]
未激活版本需要使用邮箱获取激活码，而且这个激活码只能使用7天的，当再次使用该邮箱获取激活码的时候，就说该邮箱已经注册过了的。难道未激活版需要持续使用新的邮箱来进行注册使用吗。

因为我只是看不惯Mapper使用Autowired时的error警告，用不到那么多激活版本功能的

**Comment by gejun123456** [comment]
Mapper Autowire的那个功能不用激活的，可以一直用的

**Comment by littlefisher666** [comment]
哦哦哦，好的谢谢
