### ISSUE TITLE
_parameter.get("0").XXX提示error

### ISSUE THREAD

**Issue by ywan2205** [gejun123456/MyBatisCodeHelper-Pro#632]
mybatis3.5.2
使用<if test='_parameter.get("0").XXX != null'>语句时提示<operator> expected, got '.'。有什么好办法吗？

**Comment by gejun123456** [comment]
目前不支持方法多层调用  弄个bind就行了 https://gejun123456.coding.net/p/MyBatisCodeHelper-Pro/d/MyBatisCodeHelper-Pro/git/raw/master/screenshots/ognlbindcall.png

**Comment by ywan2205** [comment]
好的，谢谢
