### ISSUE TITLE
如何添加一个action

### ISSUE THREAD

**Issue by huifer** [gejun123456/MyBatisCodeHelper-Pro#634]
![image](https://user-images.githubusercontent.com/26766909/92461396-d3c1cc00-f1fb-11ea-8f12-7b38af7777ba.png)
这样的action 是如何添加的 @gejun123456

**Comment by gejun123456** [comment]
<action class="xxxxx"
                id="MybatisSupportFromDatabaseGroup"
                text="Mybatis generator">
            <add-to-group group-id="DatabaseViewPopupMenu" anchor="first"/>
        </action>

**Comment by huifer** [comment]
thx .
