### ISSUE TITLE
使用Postgresql数据库时的问题。

### ISSUE THREAD

**Issue by jaaaar** [gejun123456/MyBatisCodeHelper-Pro#636]
- MybatiscodeHelperPro 2.8.6-183-202
- idea 2020.2.1

1. postgresql中存在多个模式, 在xml中定义 `<sql id="TABLE_NAME">"public".user</sql>`, 此处"public"模式爆红。
1. xml文件中引用枚举类的变量. 如 `del_flag = ${@ com.xxx.xxx.DelFlag@DELETED.code}` 在等号后面后爆红。提示`<expression> expected, got 'AND'`. `.code`也会爆红  
1. 在使用枚举变量后如果继续join如LEFT JOIN 则 LEFT 会爆红。提示`Unable to resolve column "LEFT"`

**Comment by gejun123456** [comment]
1. 是因为sql标签不是完全的sql 需要加个注释成为完整的sql 看文档sql标红那节
2. 爆红 是因为ognl 目前不支持多层方法调用 可以先bind下 然后调用 .code  
3. 是因为 ${} 中的sql可以是任意值 需要添加一个 $sql的注释来给一个可能的sql值 后面的sql可以提示正确和检测，可以参考文档sql标红那节

**Comment by jaaaar** [comment]
正常了
