### ISSUE TITLE
generator 无法生成除insert之外的默认方法

### ISSUE THREAD

**Issue by lantyu** [gejun123456/MyBatisCodeHelper-Pro#637]
插件版本: 2.8.6-183-202
idea版本: 2020.2.1
操作系统: windows7

问题: 使用Mybtais Generator功能, 默认勾选全部默认生成方法, 但是只生成了 insert 和 insertSelective, 其他的如update,delete,select相关的都没生成
补充:  装了群里的 最新 MybatisCodeHelperNew-2.8.7-SNAPSHOT-183-202 似乎已经fix这个问题了

**Comment by lantyu** [comment]
补充一下 刚刚发现 好像和表有关 是宽表不支持? 和插件版本无关

**Comment by gejun123456** [comment]
表没有主键导致的，其他方法可以通过方法名来生成

**Comment by gejun123456** [comment]
![UTNETT_5(FWKIX_0}V87T](https://user-images.githubusercontent.com/6340473/94354412-46142680-00ad-11eb-8191-d9887e5ea928.png)
下个版本加个提示
