### ISSUE TITLE
xml可以跳转到mapper，mapper无法跳转到xml

### ISSUE THREAD

**Issue by 2395461672** [gejun123456/MyBatisCodeHelper-Pro#649]
![image](https://user-images.githubusercontent.com/42174196/96951784-d49a8d00-151f-11eb-8bb0-1b315da94394.png)

![image](https://user-images.githubusercontent.com/42174196/96951840-f7c53c80-151f-11eb-8c06-00999010eae7.png)

xml文件可以跳转到mapper，mapper跳转不到xml。
![image](https://user-images.githubusercontent.com/42174196/96951903-26431780-1520-11eb-8833-f9c4aa9c524b.png)
zhe'ge
这个我已经试过了，还是没有解决问题，请帮我看下问题所在

**Comment by 2395461672** [comment]
![Uploading image.png…]()

**Comment by gejun123456** [comment]
加我qq 1098632410 来远程看下

**Comment by song-changwei** [comment]
请问这个问题解决了嘛？

**Comment by gejun123456** [comment]
加我qq 1098632410 来远程看下

**Comment by song-changwei** [comment]
> 请问这个问题解决了嘛？

已经好用啦，谢谢！

**Comment by islaiyp** [comment]
需要怎么操作么？我也遇到了这个问题

**Comment by gejun123456** [comment]
先检查看看有没有插件冲突，没有的话 invalidatecache restart试下 还有问题的话加我qq 1098632410 来看看
