### ISSUE TITLE
如果动态传表名，表名的别名会识别不了。虽然知道不影响但是看着很难受呀

### ISSUE THREAD

**Issue by mingyujiao** [gejun123456/MyBatisCodeHelper-Pro#652]
![image](https://user-images.githubusercontent.com/49345287/98203536-32db5d00-1f6f-11eb-8e4b-3405e6ccc67d.png)
![image](https://user-images.githubusercontent.com/49345287/98203551-3a026b00-1f6f-11eb-9d6b-8c67c3c1d83f.png)

**Comment by gejun123456** [comment]
在 ${} 上alt enter  add sql reprent for expression 填一个表名进去 就可以识别了
