### ISSUE TITLE
建议xml中支持识别java常量OGNL表达式识别

### ISSUE THREAD

**Issue by dzh6699** [gejun123456/MyBatisCodeHelper-Pro#669]
现在在sql语句里面有ognl表达式常量会标红提示报错
![image](https://user-images.githubusercontent.com/29142176/103469667-b4e6d700-4da2-11eb-8fe3-e23f87a7a714.png)

**Comment by gejun123456** [comment]
alt enter add representation for $ 在后面加个注释就行了哈，看文档安全的sql那节
