### ISSUE TITLE
群发垃圾邮件吗，想钱想疯了？

### ISSUE THREAD

**Issue by xumeng** [gejun123456/MyBatisCodeHelper-Pro#671]
> 抱歉打扰了，我是IDEA插件MybatisCodeHelperPro插件的开发，MybatisCodeHelperPro是一个Intellij idea下的插件，已经开发了4年，是第一个完整支持mybatis动态sql代码提示，代码检测的插件，在Mybatis xml中写sql几乎所有地方都有代码提示，写错有检测，不用担心sql写错，另外插件还有从表生成crud，方法名生成sql，生成testcase等其他实用功能，可大幅提升开发Mybatis的效率，节约大量时间。插件目前售价仅为99元3年，试用购买网址为：http://brucege.com/pay/view?from=EFQOYFXAPO。凭此邮件联系我微信gejun12311购买3年可再减10元。 谢谢

？？？

**Comment by mritd** [comment]
挂到 V 站，我看看多少人收到了

**Comment by gejun123456** [comment]
嗯，我的问题，抱歉，以后不会再发
