### ISSUE TITLE
可否支持 statement 字符串方式跳转

### ISSUE THREAD

**Issue by liudongmiao** [gejun123456/MyBatisCodeHelper-Pro#682]
由于某些场景，我们项目中使用的类似 statement 字符串方式。比如：

```java
selectOne("namespace.id", xxx);
```

转成新范式之后，其实就是

```java
namespace.id(xxx)
```

可否支持这种范式的跳转？

目前我们就是单纯的搜字符串，相当于没有 mybatis code helper pro 插件的原始方式。

利益相关：在解决 #677 后的商店付费用户。

**Comment by liudongmiao** [comment]
目前 IDEA 内嵌的字符串跳转有反射时直接跳到相应的字段/方法定义。

**Comment by gejun123456** [comment]
这种使用的比较少，建议用新范式那种，我看看改动大不大

**Comment by liudongmiao** [comment]
是从 ibatis 转成 mybatis 的。

xml 文件自动转的，当然修复一大堆官方不支持的标签。

调用的话，也是普通的 namespace + id，其实没有定义 mapper ...

项目比较多，全部转成新范式也比较困难。

你看看能不能支持，不能支持的，我想想办法，但其实并不想造个轮子。

**Comment by gejun123456** [comment]
![image](https://user-images.githubusercontent.com/6340473/113655529-93acc400-96cc-11eb-828f-cbcd329ffd77.png)
![image](https://user-images.githubusercontent.com/6340473/113655531-960f1e00-96cc-11eb-9376-09f81118ce57.png)

qq群文件已支持，可以试试
qq群：914051156

**Comment by gejun123456** [comment]
加了个简单的跳转，后续还可以弄里面的代码提示这些

**Comment by liudongmiao** [comment]
好的，周一到公司项目里看看是否适合～

**Comment by gejun123456** [comment]
已支持
