### ISSUE TITLE
当column名字相同是会出现警告【当前resultMap已存在相同的column名，请检查resultMap确保没问题 】，但是使用的 association 标签。能修复一下吗？

### ISSUE THREAD

**Issue by ChinaSunC** [gejun123456/MyBatisCodeHelper-Pro#683]
resultMap id="XXXXX" type="XXXXX"
        result column="**abc_id**"          property="abcId"       jdbcType="BIGINT"
        association column="**abc_id**" property="abcUrl"      javaType="java.lang.String"  select="queryAbcUrlById"
resultMap

**Comment by ChinaSunC** [comment]
<resultMap id="XXXXX" type="XXXXX">
        <result column="abc_id" property="abcId" jdbcType="BIGINT"/>
        <association column="abc_id" property="abcUrl" javaType="java.lang.String"
                     select="queryAbcUrlById"/>
</resultMap>

**Comment by gejun123456** [comment]
好，加个兼容
