### ISSUE TITLE
从数据库生成代码时，选了“生成的java字段名和表列名一样”后，如果数据库列名是大驼峰命名，生成的java字段名仍然是小驼峰命名

### ISSUE THREAD

**Issue by a1156883061** [gejun123456/MyBatisCodeHelper-Pro#695]
希望插件的行为和选项的行为一致，我需要生成的java类的字段名是大驼峰命名
使用“配置一个新方法”时，直接返回表的字段名，最终结果仍会被转为小驼峰命名
希望提供一个选项，不自动转换为小驼峰

![生成界面](https://user-images.githubusercontent.com/36263893/118775681-c6480000-b8b9-11eb-81bf-64649424189f.png)
![生成的xml](https://user-images.githubusercontent.com/36263893/118775706-ca741d80-b8b9-11eb-81b9-c5b5227b3d06.png)

**Comment by gejun123456** [comment]
需要点一下 应用 那个按钮  点一下就好了
