### ISSUE TITLE
数据库鼠标悬浮提示乱码

### ISSUE THREAD

**Issue by anjia0532** [gejun123456/MyBatisCodeHelper-Pro#696]
![image](https://user-images.githubusercontent.com/15098916/118910892-da423f00-b957-11eb-96d5-01666f6fcfdc.png)

这是idea自己的问题（记得之前版本是可以的），在database tab 页也有这个问题

经过研究发现不是 **MyBatisCodeHelper-Pro**的问题，是idea自带字体的问题。改成 Monospaced 就可以了 
![image](https://user-images.githubusercontent.com/15098916/118910975-fa71fe00-b957-11eb-8c4c-a4b44cb2c89d.png)

**Comment by anjia0532** [comment]
给idea提了issues https://youtrack.jetbrains.com/issue/DBE-13274

**Comment by gejun123456** [comment]
棒
