### ISSUE TITLE
无法自动识别java8的参数命名

### ISSUE THREAD

**Issue by fzhyzamt** [gejun123456/MyBatisCodeHelper-Pro#704]
IDEA版本：`2021.1.3`
插件版本：`2.9.3-183-204`

加了`@Param`注解的参数可以识别，但直接使用方法参数名的就会报红。
比如下边这个例子，可以识别productType，但识别不了uniqueCode；
```java
public interface ExampleDao {
    void select(@Param("productType") Integer productType, String uniqueCode);
}
```
```xml
<select id="select">
    select 1
    from example
    where product_type = #{productType}
      and unique_code = #{uniqueCode} 
</select>
```

**Comment by gejun123456** [comment]
设置里面有个 useActualParamName 勾一下就好了  
![image](https://user-images.githubusercontent.com/6340473/126428286-a317b141-48c7-4b2e-ac28-1920eb96d275.png)

**Comment by qw52655265** [comment]
系统：MACOS
IDEA版本：2023.2
插件版本：3.2.7
JDK: zulu-jdk17
JDK version: 17

EditorRole selectByConditions(String name);

![1bd7bf9c4264162ccf6b00852ec2755d](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/17700671/c1e1492f-7eba-4eec-8cf3-94338e832070)

问题：一个参数的时候无法正常提示参数名
奇怪的点：
1、2个（含）参数以上时又可以正常提示
2、其他使用JDK8的版本项目（使用上面同一个jdk），插件配置勾选上图的选项，一个参数也能正常提示
3、idea配置：build-> complier -> java complier, 也有正常配置-parameters参数

麻烦大大帮忙解答一下 @gejun123456

**Comment by gejun123456** [comment]
估计你是单个参数没加@Param注解，新版本的mybatis确实是支持这种，插件还没弄支持,单参数可以加个@Param注解或者等插件以后弄个兼容

**Comment by juoliii** [comment]
@gejun123456 插件啥时候能兼容下这个啊，被这个问题弄的头疼

**Comment by gejun123456** [comment]
下个版本优化下

**Comment by gejun123456** [comment]
![支持mybatis3 5 2ognl可以使用任意名字引用](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/6340473/a6c357ea-96bd-4b33-a9a5-ea4a6bc9309c)

**Comment by gejun123456** [comment]
群文件已支持，估计这周发布正式版

**Comment by gejun123456** [comment]
#927
