### ISSUE TITLE
不能识别resultMap分隔符，报红

### ISSUE THREAD

**Issue by nuoxd** [gejun123456/MyBatisCodeHelper-Pro#705]
![image](https://user-images.githubusercontent.com/13375605/126025618-d53f1f95-c376-4e71-83ef-49a6ce6b34bb.png)
![image](https://user-images.githubusercontent.com/13375605/126025623-1599e0bb-593d-4a5f-8c74-6abaef9a7f04.png)
![image](https://user-images.githubusercontent.com/13375605/126025628-87300324-e330-4255-af78-c7bc5ecc7651.png)
编译执行结果正常
![image](https://user-images.githubusercontent.com/13375605/126025645-02abf4cd-d760-4d23-96fd-465b15c0637a.png)
![image](https://user-images.githubusercontent.com/13375605/126025653-8a68c0f0-f7a1-45ce-9490-229d13daa809.png)

**Comment by gejun123456** [comment]
好的，我看看

**Comment by gejun123456** [comment]
官方支持这个么，没看到官方文档写了这个
