### ISSUE TITLE
SQL格式化缩进在有内嵌XML标签时的优化

### ISSUE THREAD

**Issue by JonasGao** [gejun123456/MyBatisCodeHelper-Pro#706]
如下两个SQL都是格式化后的效果。
![image](https://user-images.githubusercontent.com/4549584/126756580-855cd4fd-6451-41ed-9c7b-c41a349a7234.png)

我希望作者可以调整的主要是这部分
![image](https://user-images.githubusercontent.com/4549584/126756674-691f506a-9949-49d8-9e7b-d58fe9e17efa.png)

当 SQL 中插入类似 foreach 和 if 这些 xml 标签后，SQL 格式化的缩进就会编程 8 个空格。而不是像第一张图里的对齐。
造成上下两种格式化风格不同。希望可以保持风格相同。

像这样
![image](https://user-images.githubusercontent.com/4549584/126756923-d1345213-f3cb-471e-943f-368a079f7bb3.png)

**Comment by gejun123456** [comment]
谢谢反馈 我看看

**Comment by gejun123456** [comment]
新版本应该已经支持了

**Comment by JonasGao** [comment]
等回头试试，再有问题再回来开好了
