### ISSUE TITLE
在表模型有不需要存入数据库的自定义字段时，生成SQL时希望支持更多的手段避免报错

### ISSUE THREAD

**Issue by JonasGao** [gejun123456/MyBatisCodeHelper-Pro#707]
现在我有一个抽象模型 A，和模型 B 和 模型 C。B 和 C 都继承 A。A 中包含自定义字段。A 的自定义字段在B表上不存入数据库。但是在 C 表上需要存入。

在上述情况下，当前插件在B表上根据方法名生成SQL时，会报字段不一致错误。要求增加`@Transient`注解。但是因为这个自定义字段，C 表需要使用，所以不能增加这个注解。

![image](https://user-images.githubusercontent.com/4549584/126757723-36eb9b13-5bc0-462a-9264-95fcc8c0a634.png)

希望可以对上述情况，增加新的配置方式来避免报错，成功生成SQL。

**Comment by gejun123456** [comment]
嗯，是个问题，可以先注释掉，生成了代码 再注释回来，不过有点麻烦， 或者插件这里加个判断 是否要忽略掉这种。

**Comment by gejun123456** [comment]
2.9.5 可以以xml中的字段为准来使用
