### ISSUE TITLE
使用mysql的拼接字符串报错

### ISSUE THREAD

**Issue by fzhyzamt** [gejun123456/MyBatisCodeHelper-Pro#709]
是出于通用性的考虑不支持吗？

```xml
    <select id="test" parameterType="String" resultType="String">
        select port_name
        from d_port
        where port_name like "%"#{name}"%"
    </select>
```
![image](https://user-images.githubusercontent.com/7298496/126970539-4c100b56-12da-4a4c-b48b-6f2f57b3615a.png)
![image](https://user-images.githubusercontent.com/7298496/126970786-834866f1-aca4-41c6-a088-23751834ec6e.png)
![image](https://user-images.githubusercontent.com/7298496/126970902-8810010b-25ef-43fa-857f-e23fa4aa6447.png)

**Comment by monkeyKinn** [comment]
like CONCAT('%',#{name},'%')

**Comment by gejun123456** [comment]
或者用mybatis的bind那个
