### ISSUE TITLE
在win10高分屏下表格高度有问题

### ISSUE THREAD

**Issue by jockey1230** [gejun123456/MyBatisCodeHelper-Pro#71]
win10系统，4k分辨率，250%缩放模式下，create new mybatis files 对话框的表格高度太小，导致type列的下拉框选项内容只能看到很小一部分

**Comment by gejun123456** [comment]
有截图可以看看么。

**Comment by jockey1230** [comment]
感觉表格的高度没有随着屏幕缩放比例放大
![1518159387 1](https://user-images.githubusercontent.com/6385911/36015468-82ff90a6-0da9-11e8-9042-d1b49ea6495a.png)

**Comment by gejun123456** [comment]
好的，谢谢反馈哈。

**Comment by gejun123456** [comment]
前几个版本修了下，可以试试，先关了，有问题再联系

**Comment by jockey1230** [comment]
已经可以正常显示了☺

葛俊 <notifications@github.com> 于2018年12月7日周五 下午2:38写道：
