### ISSUE TITLE
生成Model类后缀失效

### ISSUE THREAD

**Issue by Loongrx** [gejun123456/MyBatisCodeHelper-Pro#712]
配置了生成Model类后缀失效,
idea版本为: IntelliJ IDEA 2021.1.3 (Ultimate Edition)
![image](https://user-images.githubusercontent.com/47909833/127592069-bcb18c21-0963-4c7a-9690-1fdb0bcab8f4.png)

**Comment by Loongrx** [comment]
今天突然发现可以了, 可能是要重启idea生效

**Comment by xfeng-github** [comment]
我遇到了相同的问题。。。

IntelliJ IDEA 2019.1.4 (Ultimate Edition)
Build #IU-191.8026.42, built on July 30, 2019
Licensed to https://zhile.io
You have a perpetual fallback license for this version
Subscription is active until July 8, 2089
JRE: 1.8.0_212-release-1586-b4 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by gejun123456** [comment]
表之前生成过吗，需要清理一下表缓存就行

**Comment by xfeng-github** [comment]
> 表之前生成过吗，需要清理一下表缓存就行

是的生成过，如何清理这块的缓存呢

**Comment by gejun123456** [comment]
表上右键mybatis generator 下面有个清理表缓存的按钮
