### ISSUE TITLE
建议增加查看本地运行时sql打印功能

### ISSUE THREAD

**Issue by zhihui1999** [gejun123456/MyBatisCodeHelper-Pro#713]
如题,将完整的不带?的sql打印到控制台

**Comment by gejun123456** [comment]
可以用其他log插件，如 MybatisLog 和 https://github.com/Link-Kou/intellij-mybaitslog 这种

**Comment by dyb23** [comment]
+1

**Comment by youth6966** [comment]
> 可以用其他log插件，如 MybatisLog 和 https://github.com/Link-Kou/intellij-mybaitslog 这种

跟这个插件冲突吗 ？

**Comment by gejun123456** [comment]
> > 可以用其他log插件，如 MybatisLog 和 https://github.com/Link-Kou/intellij-mybaitslog 这种
> 
> 跟这个插件冲突吗 ？

不冲突
