### ISSUE TITLE
插件是要收费了吗？升级了最新的idea后，插件不能用了，idea版本如下

### ISSUE THREAD

**Issue by yinqichao** [gejun123456/MyBatisCodeHelper-Pro#714]
IntelliJ IDEA 2021.2 (Ultimate Edition)
内部版本号 #IU-212.4746.92，July 27, 2021 构建
Licensed to ***
订阅有效期至 May 19, 2022。
运行时版本: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
macOS 11.5
GC: ParNew, ConcurrentMarkSweep
Memory: 3933M
Cores: 8
Registry: debugger.watches.in.variables=false, js.debugger.webconsole=false
Non-Bundled Plugins: Statistic (4.1.7), com.intellij.zh (212.231), com.linkkou.plugin.intellij.assistant.mybaitslog (1.0.3), org.intellij.RegexpTester (1.0.8), MyBatisLog (2021.5.1), com.alibaba.p3c.smartfox (2.1.1), org.jetbrains.plugins.vue (212.4746.57), cn.yiiguxing.plugin.translate (3.1.1), com.ccnode.codegenerator.MyBatisCodeHelperPro (2.9.4-183-204), org.asciidoctor.intellij.asciidoc (0.33.13)
Kotlin: 212-1.5.10-release-IJ4746.92

**Comment by gejun123456** [comment]
brucege.com 有激活码，可以试用或者购买
