### ISSUE TITLE
是否不支持最新版本的idea？

### ISSUE THREAD

**Issue by spontaneously5201314** [gejun123456/MyBatisCodeHelper-Pro#718]
你好，我使用的是最新版本的idea。

IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64

我在使用的过程中，仿佛这个插件的所有功能都不支持，最简单的跳转到不能，sql提示什么的也都没有。

![image](https://user-images.githubusercontent.com/16059657/133586910-0736b63a-46a8-4766-9ed5-2895868c1378.png)
![image](https://user-images.githubusercontent.com/16059657/133586970-1a7726be-ef63-46a8-bc67-4532ffff1d6c.png)

**Comment by gejun123456** [comment]
看看有没有插件冲突，然后invalidateCache restart 下试试，还不行联系我 微信gejun12311 来看看，这边很多人用最新版没问题的
