### ISSUE TITLE
使用的是postgresql数据库，指定匹配不到具体的schema中的表，xml报红

### ISSUE THREAD

**Issue by 535704264** [gejun123456/MyBatisCodeHelper-Pro#741]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/31807632/158993409-f2470a11-ae24-4d2d-a1da-08d98947267f.png">

**Comment by gejun123456** [comment]
配置数据库的时候database填了没，还有设置里面的dialect配置，看文档配置数据库那节，还有问题请联系我qq 1098632410 来远程看看

**Comment by 535704264** [comment]
已解决，用的pg数据库，需要指定模式，否则读取的public



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月25日(星期五) 上午10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gejun123456/MyBatisCodeHelper-Pro] 使用的是postgresql数据库，指定匹配不到具体的schema中的表，xml报红 (Issue #741)





 
配置数据库的时候database填了没，还有设置里面的dialect配置，看文档配置数据库那节，还有问题请联系我qq 1098632410 来远程看看
