### ISSUE TITLE
[Feature] 添加对 <arg /> 标签的代码提示

### ISSUE THREAD

**Issue by fanck0605** [gejun123456/MyBatisCodeHelper-Pro#748]
很多 immutable 的 POJO 类一般使用构造器进行初始化。需要用到大量的  `<idArg />` `<arg />` 标签，需要用到 name 和 resultMap 属性，但是在 [MyBatisCodeHelper-Pro](https://github.com/gejun123456/MyBatisCodeHelper-Pro) 中似乎并没有得到很好的支持。

希望可以添加对 `<arg />` 中 name 和 resultMap 的代码提示。

**Comment by gejun123456** [comment]
嗯，用的人比较少，我先看看

**Comment by gejun123456** [comment]
看了下，我弄一个

**Comment by fanck0605** [comment]
感谢

**Comment by gejun123456** [comment]
下个版本加

**Comment by gejun123456** [comment]
![image](https://user-images.githubusercontent.com/6340473/173046267-2eab7c46-15ca-456d-8a62-f45d6d4c0375.png)

**Comment by gejun123456** [comment]
https://share.weiyun.com/sYy7EJz6 试试这个版本 应该都支持了

**Comment by fanck0605** [comment]
我试了一下，可以用了！🎉

**Comment by gejun123456** [comment]
好滴，谢谢支持，欢迎继续提建议
