### ISSUE TITLE
用mybatis的@Select注解写sql，sql中用了常量字符串来拼接的话，无法正确解析

### ISSUE THREAD

**Issue by psuvjd** [gejun123456/MyBatisCodeHelper-Pro#749]
用mybatis的@Select注解写sql，sql中用了常量字符串来拼接的话，无法正确解析
<img width="964" alt="image" src="https://user-images.githubusercontent.com/16028643/163817594-c245efe6-3844-4a37-88a4-59af56d4d1f9.png">

**Comment by gejun123456** [comment]
注解还没弄支持，挪到xml的话就都支持的，alt enter 可以一键挪到xml里面

**Comment by psuvjd** [comment]
期待支持下注解哈~
一些简单的静态sql不想放到xml里
