### ISSUE TITLE
如果2个xml指向同一个Java类,xml还正常,但是Java类找不到Xml

### ISSUE THREAD

**Issue by cuisongliu** [gejun123456/MyBatisCodeHelper-Pro#75]
RT
如果2个xml指向同一个Java类,xml还正常,但是Java类找不到Xml

**Comment by gejun123456** [comment]
这两个xml 有啥区别哈，java类目前不能跳转到两个xml，另外了解下为啥会有这种情况哈

**Comment by cuisongliu** [comment]
公司规范而已，实体类映射在一个xml，其他所有的SQL单独另外存放一个xml.

**Comment by gejun123456** [comment]
好的，谢谢反馈，我想想怎么支持下。

**Comment by gejun123456** [comment]
请问下 可以看下你的截图么，java类和xml是一个module里吗，我这边试了两个xml文件 java类 可以跳转到到其中的一个文件

**Comment by cuisongliu** [comment]
正常来说是不一定在一起啊的，明天给你截图发一下。

**Comment by cuisongliu** [comment]
![1](https://user-images.githubusercontent.com/4150905/37498755-145c25c0-28fb-11e8-93b8-cb5b563764a0.jpg)
![2](https://user-images.githubusercontent.com/4150905/37498799-3a38b024-28fb-11e8-8a26-7ac0b11fc2ce.jpg)
![3](https://user-images.githubusercontent.com/4150905/37498802-3c7e5352-28fb-11e8-8883-ba6a5da881a0.jpg)

**Comment by gejun123456** [comment]
谢谢哈，我看这里xml也没有指向java类，这边的xml和java类是在同一个module么，目前只支持同一个module的关联。 project这个正在做。

**Comment by cuisongliu** [comment]
没有在同一model。不在同一model的项目还挺多，支持项目。等待新版本

**Comment by gejun123456** [comment]
1.7.5版本支持

**Comment by gejun123456** [comment]
1.7.6发布到中央仓库了哈，可以试下
