### ISSUE TITLE
能否支持mybatis-plus的分页方法

### ISSUE THREAD

**Issue by TangTank** [gejun123456/MyBatisCodeHelper-Pro#754]
目前插件默认使用的是PageHelp分页,能否在mapper方法的ALT+ENTER提示中新增Mybatis-Plus的分页?

mybatis-plus 分页:https://baomidou.com/pages/97710a/#paginationinnerinterceptor
`
IPage<UserVo> selectPageVo(IPage<?> page, Integer state);
// or (class MyPage extends Ipage<UserVo>{ private Integer state; })
MyPage selectPageVo(MyPage page);
// or
List<UserVo> selectPageVo(IPage<UserVo> page, Integer state);
`

**Comment by gejun123456** [comment]
可以的，我优化下 检测一下是否使用了mybatisplus

**Comment by TangTank** [comment]
已经实现了吗?! 这也太快了,太赞了!!!

**Comment by gejun123456** [comment]
还没呢，哈哈，明天弄

**Comment by TangTank** [comment]
好的好的，当时看到标签是3.0.1， 还以为这么快就发布了

**Comment by gejun123456** [comment]
qq群文件加了个简单的支持，给接口加了个IPage参数 以及把返回值改成为IPage类型
