### ISSUE TITLE
choose 标签代码提示错误

### ISSUE THREAD

**Issue by fanck0605** [gejun123456/MyBatisCodeHelper-Pro#756]
choose **只会选择一个分支执行**， when 标签与 if 标签不同。
下面的语句完全正确，但是代码提示报错

![image](https://user-images.githubusercontent.com/28819315/169438223-3c73706a-b729-44df-b873-a60f61bf7e34.png)

**Comment by fanck0605** [comment]
同 https://github.com/gejun123456/MyBatisCodeHelper-Pro/issues/615

**Comment by gejun123456** [comment]
你可以在写choose when的时候 用alt enter 有个菜单把其他分支设为ignore 就有代码提示了

**Comment by gejun123456** [comment]
貌似可以搞一个在编辑choose whe的时候 自动给其他条件设置为ignore
