### ISSUE TITLE
sql 引用不能使用对象

### ISSUE THREAD

**Issue by cjackeroo** [gejun123456/MyBatisCodeHelper-Pro#760]
```
<mapper namespace="com.sunforworld.lims.mapper.cost.CostConfirmMapper">
    <sql id="sel_costcustom_sql">
        yo.eo_code wtd_code,
        yo.test_type,
        cf.`id`,
        cf.`cost_code`
    </sql>
```

所有的yo、cf都提示红色错误，加入 ignore之后，第一个yo后的.号报错
![image](https://user-images.githubusercontent.com/39888162/171071173-b5a5ce5c-f0b3-47e0-a64d-402adca7ba2f.png)

**Comment by gejun123456** [comment]
这里加ignore没有，ignore只能在if test 或者choose when下生效，这个地方 加 前后缀的sql 就可以了，代码还能有自动提示
![sqlTagNoError (1)](https://user-images.githubusercontent.com/6340473/171084344-ba7029ac-102b-4b74-9030-1d9e57d5fd32.gif)

**Comment by cjackeroo** [comment]
谢谢，解决了我的代码洁癖……
