### ISSUE TITLE
mybatis sql log支持，从控制台打印出完整的sql功能去哪了

### ISSUE THREAD

**Issue by MARS-ALEX** [gejun123456/MyBatisCodeHelper-Pro#781]
mybatis sql log支持，从控制台打印出完整的sql功能去哪了

**Comment by gejun123456** [comment]
![mybatisLogSupportNew](https://user-images.githubusercontent.com/6340473/178275261-ea51c648-c4fe-49c3-b8c9-0eb054d14d55.gif)
这个

**Comment by MARS-ALEX** [comment]
好的，感谢大佬
