### ISSUE TITLE
xml文件大约2800行代码,代码提示很卡

### ISSUE THREAD

**Issue by linkai11** [gejun123456/MyBatisCodeHelper-Pro#784]
一张表字段很多,所以生成的sql很长,大约2800行,写sql的时候,代码提示就很卡
电脑是 mac-2021-16寸 m1Max芯片, 64G内存, idea设置8g内存

**Comment by gejun123456** [comment]
太长了确实容易卡  写新sql 弄一个相同namespace的新的xml试试

**Comment by linkai11** [comment]
收到,谢谢
