### ISSUE TITLE
对于中文表名和中文表字段，预览 xml 文件时会有乱码问题

### ISSUE THREAD

**Issue by 2938137849** [gejun123456/MyBatisCodeHelper-Pro#787]
如图，别人指定要求的表带有中文，使用插件自带的 xml 生成会有乱码问题
 ![Snipaste_2022-07-26_14-29-30](https://user-images.githubusercontent.com/37367930/180938923-5824b77a-bd87-4760-aa6a-4c3a21f7d6ad.png)

**Comment by 2938137849** [comment]
但是生成到文件没有问题，只有预览xml文件有问题

**Comment by 2938137849** [comment]
但是生成到文件没有问题，只有预览xml文件有问题

**Comment by gejun123456** [comment]
idea默认编码用的啥

**Comment by gejun123456** [comment]
估计是你java的编码不是utf8导致的，preivew这里没指定编码，我改一下

**Comment by gejun123456** [comment]
3.0.7 已修复

**Comment by 2938137849** [comment]
已修复，感谢
