### ISSUE TITLE
mybatis内置参数'_databaseId'识别标红

### ISSUE THREAD

**Issue by LmangM** [gejun123456/MyBatisCodeHelper-Pro#797]
![image](https://user-images.githubusercontent.com/95467539/185275360-e52ff622-da41-47aa-b6e7-9cbae5312754.png)

**Comment by gejun123456** [comment]
![E%516 YAI8248}3~HHR3~FR](https://user-images.githubusercontent.com/6340473/185827181-8be240b4-9c40-4793-a9fa-9fa0e76bc8e9.jpg)
3.0.9会支持，qq群文件可以先下载

**Comment by gejun123456** [comment]
已支持
