### ISSUE TITLE
2个激活码中其中1个无法激活，请问如何联系？

### ISSUE THREAD

**Issue by CodingOX** [gejun123456/MyBatisCodeHelper-Pro#82]
hi,购买了激活码，其中一个无法激活，请问如何联系？

**Comment by gejun123456** [comment]
加我微信哈 gejun12311

**Comment by gejun123456** [comment]
问题解决了么。

**Comment by CodingOX** [comment]
不好意思，因为周末不在加，现在才看到。
我明天周一联系您！
有1个激活码可以激活，另外一个不能激活！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
