### ISSUE TITLE
idea版本和插件的版本是否存在兼容的问题

### ISSUE THREAD

**Issue by GuiltyConscience** [gejun123456/MyBatisCodeHelper-Pro#823]
点击表名无法跳转到表 插件生成的增删改查也存在问题
![image](https://user-images.githubusercontent.com/39233150/203832329-45b4cab4-e56b-413b-83fb-fe60f899fdb4.png)
![image](https://user-images.githubusercontent.com/39233150/203832476-6072eaac-742f-4088-bf16-bc8909e76b2c.png)

**Comment by gejun123456** [comment]
idea改了快捷键 alt shift b 可以跳转到表

**Comment by gejun123456** [comment]
这里没生成 是因为你勾了mybatisplus 或者tkmapper， 用他们自带的baseMapper里面的方法， VARCHAR标红是因为你没加Mybatis的依赖

**Comment by GuiltyConscience** [comment]
好的谢谢  我试试看看
