### ISSUE TITLE
project的 typeAlias配置建议增加通配的方式配置

### ISSUE THREAD

**Issue by fun-li** [gejun123456/MyBatisCodeHelper-Pro#828]
## project的 typeAlias配置建议增加通配的方式配置
一般实体类的包名后缀都相同，现在的插件版本在多模块开发时需要依次配置，建议增加通配符的配置方案

**Comment by gejun123456** [comment]
![typeAlias解析](https://user-images.githubusercontent.com/6340473/207497192-9993ae5f-c448-499f-bc06-5c49a12bc136.gif)
先加了个按钮，把**对应的包名弄上去就行

**Comment by fun-li** [comment]
> ![typeAlias解析](https://user-images.githubusercontent.com/6340473/207497192-9993ae5f-c448-499f-bc06-5c49a12bc136.gif)
> 
> 先加了个按钮，把**对应的包名弄上去就行

国内版本没有推送3.1.4吧

**Comment by gejun123456** [comment]
还没发布，qq群文件
![image](https://user-images.githubusercontent.com/6340473/207502240-28073a1c-db9f-4de2-a0c1-4f1b3e11eb80.png)
