### ISSUE TITLE
generate sql fragment 的UI界面显示BUG

### ISSUE THREAD

**Issue by maruiliangjava** [gejun123456/MyBatisCodeHelper-Pro#832]
下方还有个功能
sqlWithAliasWithAs
由于这张表字段很多,导致功能界面显示不全; 无法下拉滚动;
![图片](https://user-images.githubusercontent.com/48038945/208280628-29b33cfb-32a4-4a33-a951-3970680ba2b2.png)
![图片](https://user-images.githubusercontent.com/48038945/208280685-1dcbe640-d859-403d-9830-4f56648fe569.png)

**Comment by gejun123456** [comment]
ok 我优化一下

**Comment by gejun123456** [comment]
群文件已修复
