### ISSUE TITLE
需求：Test for mybatis xml 界面添加“选定所有”，”取消选定” 按钮

### ISSUE THREAD

**Issue by zhuhongcai** [gejun123456/MyBatisCodeHelper-Pro#842]
需求：Test for mybatis xml 界面添加“选定所有”，”取消选定” 按钮

**Comment by zhuhongcai** [comment]
![QQ图片20230104153357](https://user-images.githubusercontent.com/15398640/210505570-3c715712-e952-4417-8415-2dbd6dca2eb2.jpg)

**Comment by gejun123456** [comment]
已支持
