### ISSUE TITLE
添加 lombok @Accessors 支持

### ISSUE THREAD

**Issue by syrm-ll** [gejun123456/MyBatisCodeHelper-Pro#855]
现在的 lombok 设置:
![image](https://user-images.githubusercontent.com/40515646/221423180-215f37d1-afd6-400c-9408-417cff94da4c.png)

可否添加 `@Accessors(chain = true)` 选项 (必须包含 chain = true)  省的手动加了
作用就是给所有 set 方法, 返回值由 void 改为 this, 以支持链式调用:
```java
SysUser user = new SysUser()
            .setUsername("")
            .setPassword("")
            .setAvatar("");
```

作为 `@Builder` 一种简单替代方案挺棒的

## 参考

<https://projectlombok.org/features/experimental/Accessors>

---
另外 `javax validation` 挺尴尬的, 现在同时存在两套API :
`jakarta.validation:jakarta.validation-api:3.0.2`  和 `javax.validation:validation-api:2.0.1.Final`
很多时候类路径也同时存在这两套的 jar 包, 没法区分

**Comment by gejun123456** [comment]
3.1.7 会支持这个
