### ISSUE TITLE
xml里出现多个排序方式的时候，存在错误高亮提醒的问题，以及格式化后xml结构会乱的问题

### ISSUE THREAD

**Issue by yinqichao** [gejun123456/MyBatisCodeHelper-Pro#861]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/40418422/227075343-fe7297d1-24cc-4df1-845c-8b33c1d98c74.png">

**Comment by gejun123456** [comment]
看文档安全的sql那节，需要加ignore注释才能解析

**Comment by yinqichao** [comment]
可以了，至少不红了
<img width="455" alt="image" src="https://user-images.githubusercontent.com/40418422/227133201-8c0e0f01-b11e-4387-9f03-00a11acb6661.png">

**Comment by gejun123456** [comment]
是的，还可以在编辑的代码的时候 把这个ignore去掉就有代码提示了
