### ISSUE TITLE
mapper.xml无法映射跨模块的domain对象

### ISSUE THREAD

**Issue by linnyr0623** [gejun123456/MyBatisCodeHelper-Pro#892]
在运行RuoYi-Vue项目的时候，所有mapper.xml里resultMap的type和parameterType若填写跨模块的domain对象类名，无法自动映射而报红。
<img width="1548" alt="图片" src="https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/96645657/e0000485-9421-4ba6-be0a-9d01a730945a">
<img width="1548" alt="图片" src="https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/96645657/3a85ac52-a69c-465b-83e4-79cbf8fdd22b">

**Comment by gejun123456** [comment]
正好有个视频讲这个 https://www.bilibili.com/video/BV17L411m7oz/?spm_id_from=333.999.0.0&vd_source=b12e4082cc5c34158b61ac5689b2b0d2  配置一下typeAlias就可以解析了
