### ISSUE TITLE
支持 #{} 中使用 [] 操作

### ISSUE THREAD

**Issue by gejun123456** [gejun123456/MyBatisCodeHelper-Pro#902]

**Comment by meiMingle** [comment]
这正是目前需要的，

**Comment by gejun123456** [comment]
![image](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/6340473/6da0ac72-2800-4a27-b639-94c6b487c380)
3.2.2 支持

**Comment by gejun123456** [comment]
群文件可以下载，可以试试
