### ISSUE TITLE
xml文件 #{validEndTime}  花括号内现在不会自动补全了

### ISSUE THREAD

**Issue by 759855630** [gejun123456/MyBatisCodeHelper-Pro#934]
![image](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/45380727/5a77e58a-6951-4d36-ab6e-763acb577322)
现在在xml文件中#{} 花括号里没有自动补全了，以前是可以的；if test 后面正常补全提示
插件版本：3.2.3

**Comment by gejun123456** [comment]
是不是禁用了kotlin插件

**Comment by gejun123456** [comment]
群文件可以下载到修复的版本

**Comment by 759855630** [comment]
kotlin插件一直都是禁用的，我去加群试试
