### ISSUE TITLE
findAll方法不能生成所有字段的iftest

### ISSUE THREAD

**Issue by haiyangtao** [gejun123456/MyBatisCodeHelper-Pro#938]
插件版本3.2.4 ，idea版本2023.1.4   接口写了findAll方法后，选中生成 sql with if test的选项后，xml文件里没有生成各个字段的iftest

![image](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/43634994/3d2bb0d7-0c18-418b-b785-157eb984077a)

**Comment by gejun123456** [comment]
用 findByAll方法名

**Comment by haiyangtao** [comment]
好的，非常感谢，我一会试下。
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月22日 11:58 |
| 收件人 | ***@***.***> |
| 抄送人 | haiyangtao ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [gejun123456/MyBatisCodeHelper-Pro] findAll方法不能生成所有字段的iftest (Issue #938) |

用 findByAll方法名
