### ISSUE TITLE
idea升级2023.2后出现相关bug

### ISSUE THREAD

**Issue by jysc1234** [gejun123456/MyBatisCodeHelper-Pro#948]
1. `<if test="">`语句不会出现接口内定义的字段提醒
2. `<foreach collection="">`标签也不会出现接口内定义的字段提醒，同时item内自定义命名的字段在循环里也不会智能提示

版本是最新的3.2.5

**Comment by jysc1234** [comment]
![CleanShot 2023-10-26 at 09 17 53@2x](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/148929544/8cef007e-56f2-4912-8ece-378c87780e51)
像这样光标就在那里闪，不像以前那样出现提示

**Comment by jysc1234** [comment]
![CleanShot 2023-10-26 at 10 01 42@2x](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/148929544/64f42412-724d-4b03-b208-9554eb5d663a)

**Comment by gejun123456** [comment]
看下你的接口方法参数

**Comment by jysc1234** [comment]
> 看下你的接口方法参数

![CleanShot 2023-10-26 at 11 16 32@2x](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/148929544/98d21fc9-936c-4003-9bce-3cd40f6d3ea0)
![CleanShot 2023-10-26 at 11 16 56@2x](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/148929544/e440a838-f81b-4605-abcd-4c3f5b471486)

**Comment by gejun123456** [comment]
![image](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/6340473/5603b591-0be4-4cb6-95c2-82e3eb20aaf4)
我这边没啥问题 可以检查下你的language injection配置 有没有非builtIn的
或者加我微信gejun12311来远程看看
