### ISSUE TITLE
我使用后出现了这个问题，主要是发现当${}用到被查的字段时就会爆红，但其实这段代码可以正常运行，还有就是当在标签<where>后使用DESC排序时，他会把后面的limit识别为表

### ISSUE THREAD

**Issue by wtf-ff** [gejun123456/MyBatisCodeHelper-Pro#986]
![Snipaste_2024-04-24_17-28-49](https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/107481665/9da45f23-bc26-4cce-b310-ab3f4eb26683)

**Comment by wtf-ff** [comment]
我只是一个刚开始学的萌新，希望有大佬看看

**Comment by gejun123456** [comment]
看文档这里哈 https://brucege.com/doc/#/sqlred 使用$ 表达式标红那里，加个注释就能解析了

**Comment by wtf-ff** [comment]
太感谢了，已解决，我会多看文档的，万分感谢

**Comment by wtf-ff** [comment]
太感谢了，已解决，我会多看文档的，万分感谢
