### ISSUE TITLE
驼峰体/下划线 可设置

### ISSUE THREAD

**Issue by PhoenixZeng** [gejun123456/MyBatisCodeHelper-Pro#99]
database
```
varchar   test_column_hello
```
--->
javaClass
```
String test_column_hello或者testColumnHello
```

**Comment by gejun123456** [comment]
是指通过java类生成crud代码的时候可以设置吗， 还是指通过数据库使用mybatis generator的时候支持这个哈。

**Comment by PhoenixZeng** [comment]
指数据库使用mybatis generator的时候支持这个  实体类好了之后在crud都自动是相应的了呗. 主要是 现在默认是驼峰体. 之前有几个老项目是下划线 导致重构代码的时候前端网页大量代码需要改(因为转json)

**Comment by gejun123456** [comment]
ok 可以在生成的时候加一个useactualcolumnnames的配置

**Comment by gejun123456** [comment]
[MyBatisCodeHelper-Pro-1.7.7.zip](https://github.com/gejun123456/MyBatisCodeHelper-Pro/files/1957564/MyBatisCodeHelper-Pro-1.7.7.zip)

加了下这个，可以试试

**Comment by PhoenixZeng** [comment]
useactualcolumnnames 指的是使用数据库默认的列明是吧?

**Comment by gejun123456** [comment]
是的 java对象的字段名和数据库字段的列名一样

**Comment by PhoenixZeng** [comment]
测试了一下 似乎没什么问题. 只不过弹出的窗口(就是问你要不要加注释,要不要useactualcolumnnames)的那个窗口)有点小.显示不全.

**Comment by gejun123456** [comment]
有截图可以看下么,我看看哈

**Comment by PhoenixZeng** [comment]
咦.好像就首次显示不全.现在不能重现了.

**Comment by gejun123456** [comment]
我先关掉了哈，有问题再反馈。

**Comment by zhangxiongbiao** [comment]
能否添加一个转换大小写的操作，数据库字段名称全部大写并且以下划线分隔，程序中希望生成的对象是小写且以下划线分隔
