### ISSUE TITLE
能不能搞个设置语言的选项

### ISSUE THREAD

**Issue by mowei1600** [gejun123456/MyBatisCodeHelper-Pro#991]
我发现用2024的版本idea插件是英文的，看的有点难受
能不能搞个设置语言的选项，可以选择中英文

**Comment by gejun123456** [comment]
<img width="770" alt="image" src="https://github.com/gejun123456/MyBatisCodeHelper-Pro/assets/6340473/95ae8291-5da5-41db-8476-a9b8e186ef9a">
试试这个

**Comment by mowei1600** [comment]
三个方法都不行

**Comment by gejun123456** [comment]
可以加我微信gejun12311 或者 qq 1098632410 来看看

**Comment by gejun123456** [comment]
搞定了吗，咋搞定的

**Comment by mowei1600** [comment]
> 搞定了吗，咋搞定的

不想安装中文插件，只能说，凑合用把
